import type { PromptSample } from "./seed-tutorials";

const content: Record<string, { title: string; features: string[]; steps: string[]; proof: string; plans: string[]; faq: string[] }> = {
  "clearinvoice-static-saas": { title: "Billing that keeps the whole store in sync", features: ["One invoice timeline|Follow draft, delivery and payment status without switching spreadsheets.", "Reconcile with confidence|Match incoming payments to orders and flag exceptions for review.", "Know your cash position|See outstanding invoices alongside the money already collected."], steps: ["Connect your store and import the invoice register.", "Review customer details and choose payment terms.", "Send invoices and follow payment status from one queue."], proof: "A store manager starts the day with overdue invoices, resolves unmatched payments and shares a clean weekly report with the bookkeeper. This sample workflow keeps every handoff visible.", plans: ["Starter|$0 / month|20 invoices, one store, CSV export", "Growth|$29 / month|Unlimited invoices, reminders, three stores", "Team|$79 / month|Shared review queue, roles, consolidated reports"], faq: ["Can I bring existing invoices?|Import a CSV and review the mapped fields before accepting the records.", "What happens to disputed payments?|Keep them in the review queue until a teammate resolves the exception.", "Can I export my data?|Every plan includes invoice and payment exports."] },
  "taskly-liquid-glass": { title: "Give good work room to happen", features: ["A plan everyone can read|Turn the week's priorities into clear owners and next steps.", "Focus without losing context|Keep notes, decisions and the relevant files with each task.", "Progress you can trust|Spot blocked work before the weekly meeting begins."], steps: ["Create a space for the team and write the outcome.", "Break the outcome into tasks with owners and dates.", "Review the board together and unblock the next move."], proof: "The launch team reviews its board each morning: design is ready for review, engineering has one dependency, and the release checklist has an owner. The example shows a shared rhythm without another status meeting.", plans: ["Personal|Free|One workspace, personal board, weekly planning", "Team|$8 / member|Shared boards, timelines, unlimited notes", "Business|$16 / member|Team permissions, reporting, workspace templates"], faq: ["Does every task need a deadline?|No. Add dates only when the work has a real commitment.", "Can guests review work?|Invite reviewers to the relevant workspace without sharing all projects.", "Can we start with an existing plan?|Import your task list and confirm owners before publishing it."] },
  "mindloop-monochrome": { title: "From a thought worth keeping to a letter worth opening", features: ["Write with focus|A quiet draft space keeps the argument, sources and edits together.", "Curate with intent|Save reading notes and explain why each link matters to your audience.", "Publish with care|Preview the edition, check links and schedule a considered send."], steps: ["Collect a small reading list around one central question.", "Shape a draft with a clear opening, argument and takeaway.", "Send a preview to an editor before scheduling the edition."], proof: "In this editorial workflow, one writer collects research on Monday, an editor sharpens the argument on Wednesday, and Friday's edition ends with a question for readers. Quality comes from a repeatable review, not a louder inbox.", plans: ["Notebook|Free|Private drafts, reading list, edition previews", "Publication|$15 / month|Scheduled editions, subscriber groups, archive", "Editorial team|$45 / month|Shared review, contributor roles, publication analytics"], faq: ["Can I keep a draft private?|Drafts stay private until you deliberately publish an edition.", "Can readers find older editions?|Publish selected letters to your archive and keep others subscriber-only.", "Can I leave with my writing?|Export your editions and subscriber list at any time."] },
  "velorah-cinematic": { title: "Digital spaces with a slower heartbeat", features: ["Strategy before screens|Find the audience, the purpose and the one thing the experience must do well.", "A visual language of your own|Build a focused palette, considered typography and a coherent motion rhythm.", "Craft through delivery|Carry the original direction through responsive layouts and final review."], steps: ["Discovery: map the audience and agree on the project brief.", "Direction: explore the story through typography and a working page.", "Delivery: refine the experience across screens and document the system."], proof: "Field Notes is an example studio engagement: an independent publisher moves from a scattered portfolio to a readable archive. A restrained serif, generous margins and a clear index make the work itself the centre of attention.", plans: ["Direction|Two weeks|Research, creative brief, visual direction", "Experience|Six weeks|Content structure, responsive design, working prototype", "Partnership|Monthly|Ongoing design review, new pages, system stewardship"], faq: ["Where does a project begin?|With a conversation about your audience, content and the decision the site should support.", "Do you work with an existing identity?|Yes. We review its strengths before deciding what needs to evolve.", "What do we receive at handoff?|The working design, reusable styles and clear notes for the team maintaining it."] },
  "daon-korean-saas": { title: "정산은 차근차근, 매장 운영은 가볍게", features: ["정산 내역 한곳에|은행·카드사·PG 내역을 모아 입금 예정일과 실제 입금을 비교해요.", "놓친 항목 확인|수수료 차이와 미입금 내역을 따로 모아 검토할 수 있어요.", "매장별 손익 보기|매출과 비용을 함께 확인해 다음 달 운영 계획을 세워요."], steps: ["정산 내역을 가져오고 매장 정보를 확인해요.", "입금 내역과 수수료를 비교해 다른 항목을 검토해요.", "월간 보고서를 내려받아 담당자와 공유해요."], proof: "동네 카페의 하루를 예로 들었어요. 사장님은 오전에 입금 예정 내역을 확인하고, 누락된 항목만 검토한 뒤 월말 자료를 세무 담당자에게 전달해요. 아래 가격과 사례는 제품 디자인을 위한 예시예요.", plans: ["무료|월 0원|매장 1개, 월간 요약, 내역 내려받기", "프로|월 19,000원|정산 비교, 수수료 검토, 입금 알림", "비즈니스|월 49,000원|매장별 손익, 담당자 권한, 통합 보고서"], faq: ["기존 엑셀 자료도 쓸 수 있나요?|파일을 가져온 뒤 날짜와 금액 열을 확인하고 등록할 수 있어요.", "세금 신고도 자동으로 되나요?|검토용 정산 자료를 정리해요. 실제 신고는 담당자와 확인해 진행해 주세요.", "이용을 멈추면 자료는 어떻게 되나요?|필요한 정산 내역을 먼저 내려받아 보관할 수 있어요."] },
};
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll('"', "&quot;");
export const landingSectionStyles = `
.landing-sections{width:min(1120px,calc(100% - 40px));margin:0 auto;color:var(--fg);font:16px/1.7 system-ui,sans-serif}
.landing-sections>section{padding:88px 0;border-top:1px solid var(--line)}
.landing-sections h2{font-size:clamp(28px,4vw,48px);line-height:1.15;letter-spacing:-.04em;max-width:800px;margin:0 0 32px}
.landing-sections h3{font-size:21px;margin:0 0 12px}.landing-sections p{color:var(--muted);line-height:1.8}
.landing-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.landing-grid article{padding:28px;border:1px solid var(--line);border-radius:20px;background:var(--panel)}
.landing-steps{counter-reset:step;display:grid;gap:20px;list-style:none;padding:0}.landing-steps li{padding:24px;border-bottom:1px solid var(--line)}.landing-steps li:before{counter-increment:step;content:'0' counter(step);color:var(--accent);font-size:28px;margin-right:28px}
.landing-story{display:grid;grid-template-columns:1fr 1.3fr;gap:48px;align-items:start}.landing-sections details{padding:22px 0;border-bottom:1px solid var(--line)}.landing-sections summary{cursor:pointer;font-weight:650}.landing-sections small{color:var(--muted)}
@media(max-width:700px){.landing-grid,.landing-story{grid-template-columns:1fr}.landing-sections>section{padding:56px 0}}
`;
export function renderLandingSections(sample: PromptSample): string {
  const data = content[sample.slug];
  if (!data) return "";
  const korean = sample.slug === "daon-korean-saas";
  return `<div class="landing-sections">
<section id="features" data-bg-node-id="landing-features"><h2>${escape(data.title)}</h2><div class="landing-grid">${data.features.map((item, i) => { const [title, body] = item.split("|"); return `<article data-bg-node-id="feature-${i}"><h3>${escape(title!)}</h3><p>${escape(body!)}</p></article>`; }).join("")}</div></section>
<section id="workflow" data-bg-node-id="landing-workflow"><h2>${korean ? "처음부터 월말까지, 세 단계" : "A clear path from start to finish"}</h2><ol class="landing-steps">${data.steps.map((step) => `<li>${escape(step)}</li>`).join("")}</ol></section>
<section id="reviews" data-bg-node-id="landing-story" class="landing-story"><h2>${korean ? "하루의 업무에 대입해 보세요" : "See it in a working day"}</h2><div><p>${escape(data.proof)}</p><small>${korean ? "설명을 위한 가상 사례" : "Illustrative scenario, not a customer testimonial"}</small></div></section>
<section id="pricing" data-bg-node-id="landing-pricing"><h2>${korean ? "필요한 만큼 시작하세요" : "Choose the scope that fits"}</h2><div class="landing-grid">${data.plans.map((plan) => { const [name, price, detail] = plan.split("|"); return `<article><h3>${escape(name!)}</h3><strong>${escape(price!)}</strong><p>${escape(detail!)}</p></article>`; }).join("")}</div><small>${korean ? "모든 요금은 디자인 예시이며 실제 결제가 발생하지 않아요." : "Sample plans for this design; no purchase or signup is processed."}</small></section>
<section id="faq" data-bg-node-id="landing-faq"><h2>${korean ? "시작하기 전에 궁금한 점" : "Before you begin"}</h2>${data.faq.map((item) => { const [question, answer] = item.split("|"); return `<details><summary>${escape(question!)}</summary><p>${escape(answer!)}</p></details>`; }).join("")}</section>
</div>`;
}
