import { afterEach, beforeAll, beforeEach, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { runMigrations } from "../src/db/migrate-local";
import { getSqlite } from "../src/db/sqlite-client";
import { projectsDir } from "../src/lib/paths";
import { ArtifactCoordinator } from "../src/services/artifact-coordinator";
import { inspectCanonicalTree } from "../src/services/canonical-tree-manifest";
import { interruptUserTurn, startUserTurn, type TurnDependencies } from "../src/services/turns";
import { settleProcessStreams } from "../src/adapters/process-streams";
import { closeOwnedProcess, spawnOwnedProcess } from "../src/adapters/owned-process";
import { sessionRoutes } from "../src/routes/session";
import { insertNormalizedEvent } from "../src/db/events";
import { insertAttachment } from "../src/db/attachments";
import { createHash } from "node:crypto";
import { PDFDocument } from "pdf-lib";
import { broker } from "../src/services/broker";
import { managedFileRoutes } from "../src/routes/managed-files";
import { selectContextAttachments } from "../src/services/context";
import { createApp } from "../src/server";

let projectId: string;
let sessionId: string;
let projectDir: string;
let digest: string;
beforeAll(async () => { await runMigrations(); await mkdir(projectsDir, { recursive: true }); });
beforeEach(async () => {
  projectId = `review-turn-${crypto.randomUUID()}`;
  sessionId = `${projectId}-session`;
  projectDir = path.join(projectsDir, projectId);
  await mkdir(projectDir);
  await writeFile(path.join(projectDir, "index.html"), "base");
  getSqlite().prepare("INSERT INTO projects(id,name,type,dir_path,entrypoint,backend_id,created_at,updated_at) VALUES (?,?,'prototype',?,'index.html','codex',1,1)").run(projectId, projectId, projectDir);
  getSqlite().prepare("INSERT INTO sessions(id,project_id,backend_id,status,created_at,updated_at,last_active_at) VALUES (?,?,'codex','idle',1,1,1)").run(sessionId, projectId);
  digest = (await new ArtifactCoordinator(getSqlite()).initialize(projectId, projectDir)).tree_digest;
});
afterEach(async () => { getSqlite().prepare("DELETE FROM projects WHERE id=?").run(projectId); await rm(projectDir, { recursive: true, force: true }); });

function start(runAdapter: NonNullable<TurnDependencies["runAdapter"]>, text = "Create a result", reviewDesign?: TurnDependencies["reviewDesign"], attachments: readonly string[] = []) {
  const turn = startUserTurn(sessionId, { type: "user.message", text, attachments: [...attachments] }, undefined, {
    detectBackends: async () => ({ backends: [{ id: "codex", found: true, binary_path: "fixture", version: "test" }] }), runAdapter,
    reviewDesign: reviewDesign ?? (async () => ({ status: "checked", repairs: 0, result: { schema_version: 1, project_id: projectId, artifact_revision: 1, artifact_digest: digest, created_at: 1, overall_status: "ready", checks: [] } })),
  });
  if (turn === null) throw new Error("turn reservation unavailable");
  return turn;
}

test.each(["unavailable", "must_fix"] as const)("Given %s design checks When finalizing Then the prior artifact remains unchanged", async (status) => {
  const before = await inspectCanonicalTree(projectDir);
  const turn = start(async (_backend, input) => {
    await writeFile(path.join(input.projectDir, "index.html"), "<!doctype html><p>Updated</p>");
    return { exitCode: 0 };
  }, "Update a paragraph", async () => status === "unavailable"
    ? { status: "unavailable", repairs: 0, result: null }
    : { status: "checked", repairs: 2, result: { schema_version: 1, project_id: projectId, artifact_revision: 1, artifact_digest: digest, created_at: 1, overall_status: "must_fix", checks: [] } });
  await turn.promise;
  expect(await inspectCanonicalTree(projectDir)).toEqual(before);
  expect(getSqlite().prepare("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "failed" });
});

test("Given a deleted entrypoint after a failed write When continuing Then generated assets survive and only the repaired result is committed", async () => {
  let calls = 0;
  const turn = start(async (_backend, input) => {
    calls++;
    if (calls === 1) {
      await writeFile(path.join(input.projectDir, "generated.png"), "keep generated bytes");
      await rm(path.join(input.projectDir, "index.html"));
    } else {
      expect(await readFile(path.join(input.projectDir, "generated.png"), "utf8")).toBe("keep generated bytes");
      expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe("base");
      await writeFile(path.join(input.projectDir, "index.html"), "<html><body>Recovered result</body></html>");
    }
    return { exitCode: 0 };
  });
  await turn.promise;
  expect(calls).toBe(2);
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toContain("Recovered result");
  expect(getSqlite().prepare("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "committed" });
});

test("Given invalid generated HTML When finalizing Then no repair adapter runs and the prior English pages and assets remain intact", async () => {
  const english = '<!doctype html><html lang="en"><meta charset="utf-8"><body><h1>Keep my English website</h1></body></html>';
  const multilingual = '<html><meta charset="utf-8"><body><p>생각의 흐름 그대로 中文 日本語 café 🖼️</p></body></html>';
  const image = Uint8Array.from([137, 80, 78, 71, 13, 10, 26, 10, 255]);
  await new ArtifactCoordinator(getSqlite()).run({ projectId, projectDir, kind: "turn", expectedRevision: 0, expectedArtifactDigest: digest, mutate: async (stage) => {
    await writeFile(path.join(stage, "index.html"), english, "utf8");
    await mkdir(path.join(stage, "sub"));
    await writeFile(path.join(stage, "sub", "notice.htm"), multilingual, "utf8");
    await writeFile(path.join(stage, "image.png"), image);
  } });
  const before = await inspectCanonicalTree(projectDir);
  // Exact .NET CP949 GetString(UTF8.GetBytes(Korean HTML)) -> WriteAllText output.
  // TextDecoder("euc-kr") differs between Bun and Node, so keep the actual Windows bytes.
  const corrupted = Buffer.from("PGgxPj/slbfsu5Y/Pz/rqK7sq6sg5rS566qDP+a/oT88YnI+76eN65qu67G2Pz/vp53rqK3qtYU/woA/7Iew7KSILjwvaDE+PGE+Pz9PUz8/P+OFvOyKq+a/oeySleuxtiA/Py9hPg==", "base64");
  for (const [relative, bytes] of [["index.html", corrupted], ["sub/notice.htm", Uint8Array.from([60, 112, 62, 255])]] as const) {
    let calls = 0;
    const turn = start(async (_backend, input) => {
      calls += 1;
      if (calls === 1) {
        await writeFile(path.join(input.projectDir, relative), bytes);
      } else {
        // A clean exit and valid UTF-8 must not authorize an unsolicited rewrite.
        await writeFile(path.join(input.projectDir, relative), "<html><body>Unrequested rewrite</body></html>");
        await writeFile(path.join(input.projectDir, "image.png"), "replaced image");
      }
      return { exitCode: 0 };
    });
    await turn.promise;
    expect(calls).toBe(1);
    expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe(english);
    expect(await readFile(path.join(projectDir, "sub", "notice.htm"), "utf8")).toBe(multilingual);
    expect(new Uint8Array(await readFile(path.join(projectDir, "image.png")))).toEqual(image);
    expect(await inspectCanonicalTree(projectDir)).toEqual(before);
    expect(getSqlite().prepare("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "failed" });
    const error = getSqlite().query<{ payload_json: string }, [string]>("SELECT payload_json FROM events WHERE session_id=? AND type='status.error' ORDER BY sequence DESC LIMIT 1").get(sessionId);
    expect(JSON.parse(error!.payload_json).code).toBe("publication_failed");
  }
});

test("Given prompt-directed writes When generation succeeds Then only stage changes before commit", async () => {
  const turn = start(async (_backend, input) => {
    const target = input.prompt.match(/Write or edit files inside `([^`]+)`/)?.[1];
    expect(target).toBe(input.projectDir);
    expect(target).not.toBe(projectDir);
    await writeFile(path.join(target!, "index.html"), "success");
    expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe("base");
    await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "chat.delta", turnId: input.turnId, text: "1. Red. 2. Blue." });
    await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "status.idle", stopReason: "end_turn" });
    return { exitCode: 0 };
  });
  await turn.prepared;
  await turn.promise;
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe("success");
  expect(existsSync(path.join(projectDir, ".meta", "checkpoints", `${turn.turnId}.json`))).toBe(true);
  const followup = start(async (_backend, input) => {
    expect(input.prompt).toContain("1. Red. 2. Blue.");
    expect(input.prompt).toContain("<burnguard-conversation-v1>");
    return { exitCode: 0 };
  }, "Use the second option");
  await followup.promise;
});

test("Given many historical documents When selecting persistent context Then current and named originals take priority within intake limits", () => {
  const docs = Array.from({ length: 12 }, (_, index) => ({ id: `doc-${index}`, session_id: "s", turn_id: "old", file_path: `/stored/${index}.pdf`, mime_type: "application/pdf", original_name: `${index}.pdf`, size_bytes: 4 * 1024 * 1024, sha256: "a".repeat(64), source_role: "ordinary_content" as const, source_role_explicit: false, created_at: index }));
  const paths = selectContextAttachments(docs, [docs[1]!.file_path], "0.pdf 다시 읽어 주세요");
  expect(paths[0]).toBe(docs[1]!.file_path);
  expect(paths[1]).toBe(docs[0]!.file_path);
  expect(paths.length).toBe(6);
  expect(selectContextAttachments(docs.map(item => ({ ...item, size_bytes: 10 })), [], "")).toHaveLength(8);
});

test("Given a reopened session with an earlier PDF and no extracted sidecar When a follow-up is sent without reattaching Then original and recovered text are readable", async () => {
  await mkdir(path.join(projectDir, ".attachments"));
  const pdf = await PDFDocument.create();
  pdf.addPage().drawText("PRESERVE THE ORIGINAL BRIEF");
  const bytes = await pdf.save();
  const source = path.join(projectDir, ".attachments", "saved-brief.pdf");
  await writeFile(source, bytes);
  await insertAttachment({ sessionId, turnId: "previous-turn", filePath: source, mimeType: "application/pdf", originalName: "기획서.pdf", sizeBytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") });
  let read = false;
  const turn = start(async (_backend, input) => {
    const original = input.prompt.match(/source_path: (.+?) \(read-only document/)?.[1];
    const extracted = input.prompt.match(/extracted_text_path: (.+?) \(safe text version/)?.[1];
    expect(original).toBeDefined();
    expect(new Uint8Array(await readFile(original!))).toEqual(new Uint8Array(bytes));
    expect(await readFile(extracted!, "utf8")).toContain("PRESERVE THE ORIGINAL BRIEF");
    expect(input.prompt).not.toContain("do not Read/Glob/Bash this file");
    read = true;
    return { exitCode: 0 };
  }, "원문 그대로 다시 작업해 주세요");
  await turn.promise;
  expect(read).toBe(true);
  expect(new Uint8Array(await readFile(source))).toEqual(new Uint8Array(bytes));
});

test("Given a running generation When staged HTML changes Then draft files and in-app reports work before commit and expire afterward", async () => {
  let resolveChange: (event: Extract<import('@bg/shared').NormalizedEvent, { type: 'artifact.preview' }>) => void = () => {};
  const changed = new Promise<Extract<import('@bg/shared').NormalizedEvent, { type: 'artifact.preview' }>>(resolve => { resolveChange = resolve; });
  const unsubscribe = broker.subscribe(sessionId, event => { if (event.type === "artifact.preview" && event.active && event.version >= 2) resolveChange(event); });
  let previewUrl = "";
  let observed = false;
  try {
    const turn = start(async (_backend, input) => {
      await writeFile(path.join(input.projectDir, "index.html"), "<html><body><h1>First section</h1></body></html>");
      const event = await changed;
      previewUrl = `/api/projects/${projectId}/preview/${event.previewId}/fs/index.html`;
      const app = createApp({ capability: "preview-test", appAuthority: "127.0.0.1:14070" });
      const url = `http://127.0.0.1:14070${previewUrl}`;
      expect((await app.request(new Request(url, { headers: { host: "127.0.0.1:14070" } }))).status).toBe(403);
      const response = await app.request(new Request(url, { headers: { host: "127.0.0.1:14070", "x-burnguard-capability": "preview-test" } }));
      expect(response.status).toBe(200);
      expect(await response.text()).toContain("First section");
      expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe("base");
      expect(response.headers.get("X-Burnguard-Artifact-Digest")).toBeNull();
      expect((await managedFileRoutes.request(previewUrl.replace("index.html", ".attachments/private.css"))).status).toBe(404);
      const reportUrl = previewUrl.replace("fs/index.html", "report");
      const report = { version: event.version, width: 1200, height: 800, images: 2, brokenImages: 1, pendingImages: 0, horizontalOverflow: 20 };
      expect((await managedFileRoutes.request(reportUrl, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(report) })).status).toBe(200);
      expect(JSON.parse(await readFile(path.join(path.dirname(input.projectDir), "preview-report.json"), "utf8")).brokenImages).toBe(1);
      expect((await managedFileRoutes.request(reportUrl, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...report, instructions: "untrusted" }) })).status).toBe(409);
      observed = true;
      return { exitCode: 0 };
    });
    await turn.promise;
    expect(observed).toBe(true);
    expect((await managedFileRoutes.request(previewUrl)).status).toBe(404);
    expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toContain("First section");
    expect(existsSync(path.join(projectDir, "preview-report.json"))).toBe(false);
  } finally { unsubscribe(); }
});

for (const reviewFails of [false, true]) test(`Given a deck generation When mandatory copy review ${reviewFails ? "fails" : "succeeds"} Then publication ${reviewFails ? "rolls back" : "includes corrections"}`, async () => {
  getSqlite().prepare("UPDATE projects SET type='slide_deck' WHERE id=?").run(projectId);
  const runtime = '<script src="runtime/deck-stage.js"></script>';
  let calls = 0;
  const turn = start(async (_backend, input) => {
    calls += 1;
    expect(input.generation?.effort).toBe("low");
    if (calls === 1) {
      const plan = input.prompt.match(/\.burnguard-inputs\/phases-[A-Z0-9]+\/plan\.json/)![0];
      await writeFile(path.join(input.projectDir, plan), JSON.stringify({ units: ["Title"] }));
      await writeFile(path.join(input.projectDir, "index.html"), '<section class="deck-slide" data-slide data-bg-unit="1"><h1>Placeholder</h1></section>' + runtime);
    } else if (calls === 2) await writeFile(path.join(input.projectDir, "index.html"), '<section class="deck-slide" data-slide data-bg-unit="1" data-bg-complete="true"><h1>Draft</h1></section>' + runtime);
    else {
      const { DECK_REVIEW_PROMPT } = await import("../src/harness/skills/deck-skill");
      const { IMAGE_ARTBOARD_COMPLETION_CHECKS } = await import("../src/harness/design-craft");
      expect(input.prompt).toContain(DECK_REVIEW_PROMPT);
      expect(input.prompt.split(IMAGE_ARTBOARD_COMPLETION_CHECKS)).toHaveLength(2);
      expect(input.prompt).toContain("--deck-font-heading");
      expect(input.prompt).toContain("including every slide");
      if (reviewFails) return { exitCode: 1 };
      await writeFile(path.join(input.projectDir, "index.html"), '<section data-slide><h1>Reviewed wording</h1></section>' + runtime);
    }
    return { exitCode: 0 };
  }, "Create a large slide deck");
  await turn.promise;
  expect(calls).toBe(reviewFails ? 5 : 3);
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe(reviewFails ? "base" : '<section data-slide><h1>Reviewed wording</h1></section>' + runtime);
  const reviewTools = getSqlite().query<{ payload_json: string }, [string]>("SELECT payload_json FROM events WHERE session_id=? AND type IN ('tool.started','tool.finished') ORDER BY sequence").all(sessionId)
    .map(row => JSON.parse(row.payload_json)).filter(event => event.turnId === turn.turnId && !String(event.tool).startsWith("generation_phase_"));
  expect(reviewTools.map(event => [event.type, event.tool, event.ok ?? null])).toEqual([["tool.started", "generation_deck_review", null], ["tool.finished", "generation_deck_review", !reviewFails]]);
});

test("Given a deck generation that finished When the mandatory copy review fails Then no chat.message_end is released and the refusal names the turn", async () => {
  getSqlite().prepare("UPDATE projects SET type='slide_deck' WHERE id=?").run(projectId);
  const before = await inspectCanonicalTree(projectDir);
  const events: import("@bg/shared").NormalizedEvent[] = [];
  const unsubscribe = broker.subscribe(sessionId, event => { events.push(event); });
  let calls = 0;
  try {
    const turn = start(async (_backend, input) => {
      calls++;
      if (input.turnId.endsWith("-review")) return { exitCode: 1 };
      await writeFile(path.join(input.projectDir, "index.html"), '<section data-slide><h1>Finished</h1></section><script src="/runtime/deck-stage.js"></script>');
      await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "chat.delta", turnId: input.turnId, text: "Saved the deck." });
      await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "chat.message_end", turnId: input.turnId });
      await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "status.idle", stopReason: "end_turn" });
      return { exitCode: 0 };
    }, "Update wording");
    await turn.promise;
    expect(calls).toBe(4);
    expect(events.filter(event => event.type === "chat.message_end")).toEqual([]);
    expect(events.filter(event => event.type === "status.idle").map(event => event.stopReason)).toEqual(["error"]);
    const errors = events.filter(event => event.type === "status.error");
    expect(errors.map(event => event.notApplied ?? null)).toEqual([{ turnId: turn.turnId, operationId: turn.operationId, repairs: 0 }]);
    expect(getSqlite().prepare("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "failed" });
    expect(await inspectCanonicalTree(projectDir)).toEqual(before);
  } finally { unsubscribe(); }
});

test("Given a provider that ends its message and then reports a fatal error When the turn refuses Then the buffered success terminals are withheld", async () => {
  const events: import("@bg/shared").NormalizedEvent[] = [];
  const unsubscribe = broker.subscribe(sessionId, event => { events.push(event); });
  try {
    const turn = start(async (_backend, input) => {
      await writeFile(path.join(input.projectDir, "index.html"), "<h1>Written before the failure</h1>");
      await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "chat.message_end", turnId: input.turnId });
      await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "status.idle", stopReason: "end_turn" });
      await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "status.error", code: "turn_failed", message: "provider failed", recoverable: false });
      return { exitCode: 0 };
    });
    await turn.promise;
    expect(events.filter(event => event.type === "chat.message_end")).toEqual([]);
    expect(events.filter(event => event.type === "status.idle").map(event => event.stopReason)).toEqual(["error"]);
    expect(getSqlite().prepare("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "failed" });
  } finally { unsubscribe(); }
});

test("Given a clean provider exit with empty content or missing imagery, then the saved output is repaired before publication", async () => {
  let calls = 0;
  const turn = start(async (_backend, input) => {
    calls++;
    await writeFile(path.join(input.projectDir, "index.html"), calls === 1 ? "<html><body><style>body{color:red}</style></body></html>" : calls === 2 ? '<h1>Product</h1><img src="missing.svg">' : "<h1>Finished content</h1>");
    return { exitCode: 0 };
  });
  await turn.promise;
  expect(calls).toBe(3);
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe("<h1>Finished content</h1>");
});

test("Given a final deck review deletes a slide despite a clean exit, then it resumes instead of publishing the truncated deck", async () => {
  getSqlite().prepare("UPDATE projects SET type='slide_deck' WHERE id=?").run(projectId);
  let calls = 0;
  const runtime = '<script src="runtime/deck-stage.js"></script>';
  const turn = start(async (_backend, input) => {
    calls++;
    const slides = calls === 2 ? "<section data-slide>One</section>" : "<section data-slide>One</section><section data-slide>Two</section>";
    await writeFile(path.join(input.projectDir, "index.html"), slides + runtime);
    return { exitCode: 0 };
  }, "Update wording");
  await turn.promise;
  expect(calls).toBe(3);
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toContain(">Two</section>");
});

test.each(["valid", "review_reorders", "interrupted"] as const)("Given a source-mapped deck When the turn is %s Then only intact correspondence can publish", async (outcome) => {
  getSqlite().prepare("UPDATE projects SET type='slide_deck',options_json=? WHERE id=?").run(JSON.stringify({
    design_brief: {
      schema_version: 1, output_type: "slide_deck", audience: "Customers", objective: "Explain the source",
      content_source: "attached", locale: "ko", brand_mode: "none", visual_mood: "formal",
      density: "balanced", output_size: "widescreen-16x9", source_page_mapping: "one_to_one",
    },
  }), projectId);
  await mkdir(path.join(projectDir, ".attachments"));
  const pdf = await PDFDocument.create();
  pdf.addPage().drawText("Source page one");
  pdf.addPage().drawText("Source page two");
  const bytes = await pdf.save();
  const source = path.join(projectDir, ".attachments", "source.pdf");
  await writeFile(source, bytes);
  await writeFile(`${source}.summary.json`, JSON.stringify({
    kind: "pdf", page_count: 2, fonts: [], colors: [], notes: [], headings: [], bodies: [], pages: [],
  }));
  await writeFile(`${source}.extracted.md`, "Source page one\nSource page two");
  const attachment = await insertAttachment({
    sessionId, turnId: "source-turn", filePath: source, mimeType: "application/pdf",
    originalName: "source.pdf", sizeBytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex"),
  });
  const deck = (pages: readonly number[]) => pages.map(page =>
    `<section data-slide data-bg-source-attachment="${attachment.id}" data-bg-source-page="${page}"><h1>Source page ${page}</h1></section>`
  ).join("") + '<script src="runtime/deck-stage.js"></script>';
  let calls = 0;
  let reviewed = false;
  const turn = start(async (_backend, input) => {
    calls++;
    const mapping = input.prompt.match(/<deck_source_page_mapping>\s*([\s\S]*?)\s*<\/deck_source_page_mapping>/)?.[1];
    expect(mapping).toBeDefined();
    expect(JSON.parse(mapping ?? "null").pages).toEqual([
      { attachmentId: attachment.id, page: 1 }, { attachmentId: attachment.id, page: 2 },
    ]);
    await writeFile(path.join(input.projectDir, "index.html"), deck(outcome === "interrupted" ? [1] : [1, 2]));
    if (outcome === "interrupted") interruptUserTurn(sessionId);
    return { exitCode: 0 };
  }, "Update wording", async (input) => {
    reviewed = true;
    if (outcome === "review_reorders") {
      await writeFile(path.join(input.adapter.projectDir, "index.html"), deck([2, 1]));
    }
    return { status: "checked", repairs: 0, result: {
      schema_version: 1, project_id: projectId, artifact_revision: 1, artifact_digest: digest,
      created_at: 1, overall_status: "ready", checks: [],
    } };
  });
  await turn.promise;
  expect(calls).toBe(outcome === "interrupted" ? 1 : 2);
  expect(reviewed).toBe(outcome !== "interrupted");
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe(outcome === "valid" ? deck([1, 2]) : "base");
  expect(getSqlite().query("SELECT current_revision FROM projects WHERE id=?").get(projectId))
    .toEqual({ current_revision: outcome === "valid" ? 1 : 0 });
  expect(getSqlite().query("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId))
    .toEqual({ status: outcome === "valid" ? "committed" : "failed" });
  expect(new Uint8Array(await readFile(source))).toEqual(new Uint8Array(bytes));
});

test.each([false, true])("Given two selected source documents and a reference When final review swaps documents=%s Then only selected source order publishes", async (swap) => {
  getSqlite().prepare("UPDATE projects SET type='slide_deck',options_json=? WHERE id=?").run(JSON.stringify({
    design_brief: {
      schema_version: 1, output_type: "slide_deck", audience: "Customers", objective: "Explain the sources",
      content_source: "attached", locale: "ko", brand_mode: "none", visual_mood: "formal",
      density: "balanced", output_size: "widescreen-16x9", source_page_mapping: "one_to_one",
    },
  }), projectId);
  await mkdir(path.join(projectDir, ".attachments"));
  const sources: Awaited<ReturnType<typeof insertAttachment>>[] = [];
  for (const [index, name] of ["first", "second", "reference"].entries()) {
    const pdf = await PDFDocument.create();
    pdf.addPage().drawText(name);
    const bytes = await pdf.save();
    const filePath = path.join(projectDir, ".attachments", `${name}.pdf`);
    await writeFile(filePath, bytes);
    await writeFile(`${filePath}.summary.json`, JSON.stringify({
      kind: "pdf", page_count: 1, fonts: [], colors: [], notes: [], headings: [], bodies: [], pages: [],
    }));
    await writeFile(`${filePath}.extracted.md`, name);
    const attachment = await insertAttachment({
      sessionId, turnId: "source-turn", filePath, mimeType: "application/pdf", originalName: `${name}.pdf`,
      sizeBytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex"),
      sourceRole: name === "reference" ? "immutable_reference" : "ordinary_content", sourceRoleExplicit: true,
    });
    getSqlite().prepare("UPDATE attachments SET created_at=? WHERE id=?").run(index + 1, attachment.id);
    sources.push(attachment);
  }
  const [first, second, reference] = sources;
  if (!first || !second || !reference) throw new Error("source_fixture_missing");
  const expected = [{ attachmentId: first.id, page: 1 }, { attachmentId: second.id, page: 1 }];
  const deck = (pages: typeof expected) => pages.map(source =>
    `<section data-slide data-bg-source-attachment="${source.attachmentId}" data-bg-source-page="${source.page}"><h1>Source ${source.attachmentId}</h1></section>`
  ).join("") + '<script src="runtime/deck-stage.js"></script>';
  let calls = 0;
  let reviewed = false;
  const turn = start(async (_backend, input) => {
    calls++;
    const mapping = input.prompt.match(/<deck_source_page_mapping>\s*([\s\S]*?)\s*<\/deck_source_page_mapping>/)?.[1];
    expect(JSON.parse(mapping ?? "null").pages).toEqual(expected);
    await writeFile(path.join(input.projectDir, "index.html"), deck(expected));
    return { exitCode: 0 };
  }, "Update wording", async input => {
    reviewed = true;
    if (swap) await writeFile(path.join(input.adapter.projectDir, "index.html"), deck([...expected].reverse()));
    return { status: "checked", repairs: 0, result: {
      schema_version: 1, project_id: projectId, artifact_revision: 1, artifact_digest: digest,
      created_at: 1, overall_status: "ready", checks: [],
    } };
  }, [first.file_path, reference.file_path, second.file_path]);
  await turn.promise;
  expect(calls).toBe(2);
  expect(reviewed).toBe(true);
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe(swap ? "base" : deck(expected));
  expect(getSqlite().query("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId))
    .toEqual({ status: swap ? "failed" : "committed" });
});

test("Given explicit generation options When a turn runs Then the adapter receives the validated selected model and effort", async () => {
  let observed = false;
  const generation = { model: "fixture-model", effort: "high" as const, vanilla: true, provider: "native" as const };
  const turn = startUserTurn(sessionId, { type: "user.message", text: "Create", generation }, undefined, {
    detectBackends: async () => ({ backends: [{ id: "codex", found: true, binary_path: "fixture", models: [{ id: "fixture-model", label: "Fixture", efforts: ["low", "high"] }] }] }),
    runAdapter: async (_backend, input) => { expect(input.generation).toEqual(generation); observed = true; return { exitCode: 0 }; },
    reviewDesign: async () => ({ status: "checked", repairs: 0, result: { schema_version: 1, project_id: projectId, artifact_revision: 1, artifact_digest: digest, created_at: 1, overall_status: "ready", checks: [] } }),
  });
  await turn!.promise;
  expect(observed).toBe(true);
});

test("Given a graphic project without authenticated Codex When a turn starts Then no adapter runs and the session returns to idle", async () => {
  getSqlite().prepare("UPDATE projects SET type='graphic' WHERE id=?").run(projectId);
  let invoked = false;
  const turn = start(async () => { invoked = true; return { exitCode: 0 }; });
  void turn.prepared.catch(() => {});
  await expect(turn.promise).rejects.toThrow("graphic_requires_authenticated_codex");
  expect(invoked).toBe(false);
  expect(getSqlite().query("SELECT status FROM sessions WHERE id=?").get(sessionId)).toEqual({ status: "idle" });
  expect((await inspectCanonicalTree(projectDir)).tree_digest).toBe(digest);
});

for (const failure of ["exit", "event"] as const) {
  test(`Given provider ${failure} failure after a write When generation ends Then live identity stays and no success checkpoint is written`, async () => {
    const turn = start(async (_backend, input) => {
      await writeFile(path.join(input.projectDir, "index.html"), "partial");
      if (failure === "event") await input.onEvent({ id: crypto.randomUUID(), ts: Date.now(), type: "status.error", message: "provider failed", recoverable: true });
      return { exitCode: failure === "exit" ? 1 : 0 };
    });
    await turn.promise;
    expect((await inspectCanonicalTree(projectDir)).tree_digest).toBe(digest);
    expect(getSqlite().query("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "failed" });
    expect(existsSync(path.join(projectDir, ".meta", "checkpoints", `${turn.turnId}.json`))).toBe(false);
  });
}

for (const backendId of ["claude-code", "codex"] as const) {
  test.skipIf(process.platform === "win32")(`Given ${backendId} exits without a result When the turn reaches SSE Then one bounded error and one error-idle remain visible`, async () => {
    getSqlite().prepare("UPDATE projects SET backend_id=? WHERE id=?").run(backendId, projectId);
    getSqlite().prepare("UPDATE sessions SET backend_id=? WHERE id=?").run(backendId, sessionId);
    const observed: import("@bg/shared").NormalizedEvent[] = [];
    const unsubscribe = broker.subscribe(sessionId, (event) => { observed.push(event); });
    try {
      const turn = startUserTurn(sessionId, { type: "user.message", text: "Create" }, undefined, {
        detectBackends: async () => ({
          backends: [{
            id: backendId,
            found: true,
            binary_path: "/usr/bin/false",
            version: "test",
          }],
        }),
      });
      if (turn === null) throw new Error("turn reservation unavailable");
      await turn.promise;
    } finally {
      unsubscribe();
    }

    expect(observed.filter((event) => event.type === "status.error")).toEqual([
      expect.objectContaining({ code: "turn_failed", recoverable: true }),
    ]);
    expect(observed.filter((event) => event.type === "status.idle" && event.stopReason === "error")).toHaveLength(1);
    expect(
      getSqlite()
        .query<{ readonly count: number }, [string]>(
          "SELECT COUNT(*) count FROM events WHERE session_id=? AND type='status.error'",
        )
        .get(sessionId)?.count,
    ).toBe(1);
  });
}

test.each(["Create a result", "Create 29 slides"])("Given stage writes for %s When interrupted Then stopped progress is committed before preview closes and the next turn resumes it", async (request) => {
  const events: import("@bg/shared").NormalizedEvent[] = [];
  const unsubscribe = broker.subscribe(sessionId, event => { events.push(event); });
  let entered: () => void = () => {};
  const ready = new Promise<void>((resolve) => { entered = resolve; });
  const turn = start(async (_backend, input) => {
    await writeFile(path.join(input.projectDir, "index.html"), "<html><body>partial progress</body></html>");
    await writeFile(path.join(input.projectDir, "image.png"), "generated image");
    entered();
    await new Promise<void>((resolve) => { if (input.signal?.aborted) resolve(); else input.signal?.addEventListener("abort", () => resolve(), { once: true }); });
    await writeFile(path.join(input.projectDir, "last.css"), "body{color:red}");
    throw new DOMException("Stopped", "AbortError");
  }, request);
  await ready;
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe("base");
  expect(interruptUserTurn(sessionId)).toBe(true);
  await turn.promise;
  unsubscribe();
  const committed = events.findIndex(event => event.type === "artifact.operation" && event.outcome === "committed");
  const closed = events.findIndex(event => event.type === "artifact.preview" && !event.active);
  expect(committed).toBeGreaterThanOrEqual(0);
  expect(closed).toBeGreaterThan(committed);
  expect(events.filter(event => event.type === "status.idle").map(event => event.stopReason)).toEqual(["interrupted"]);
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toContain("partial progress");
  expect(await readFile(path.join(projectDir, "last.css"), "utf8")).toBe("body{color:red}");
  expect(getSqlite().query("SELECT current_revision FROM projects WHERE id=?").get(projectId)).toEqual({ current_revision: 1 });
  expect(getSqlite().query("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "committed" });
  const snapshot = await (await sessionRoutes.request(`/api/sessions/${sessionId}/snapshot`)).json();
  expect(snapshot.data.session.status).toBe("idle");
  const continued = start(async (_backend, input) => {
    expect(await readFile(path.join(input.projectDir, "index.html"), "utf8")).toContain("partial progress");
    expect(await readFile(path.join(input.projectDir, "image.png"), "utf8")).toBe("generated image");
    await writeFile(path.join(input.projectDir, "index.html"), "<html><body>continued</body></html>");
    return { exitCode: 0 };
  });
  await continued.promise;
  expect(getSqlite().query("SELECT current_revision FROM projects WHERE id=?").get(projectId)).toEqual({ current_revision: 2 });
});

test("Given a deleted entrypoint When the writer is interrupted Then the saved entrypoint is restored and new assets survive", async () => {
  const turn = start(async (_backend, input) => {
    await writeFile(path.join(input.projectDir, "generated.png"), "partial image");
    await rm(path.join(input.projectDir, "index.html"));
    interruptUserTurn(sessionId);
    return { exitCode: 1 };
  });
  await turn.promise;
  expect(await readFile(path.join(projectDir, "index.html"), "utf8")).toBe("base");
  expect(await readFile(path.join(projectDir, "generated.png"), "utf8")).toBe("partial image");
  expect(getSqlite().query("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "committed" });
});

test("Given a stopped writer with invalid UTF-8 When preserving progress Then corrupt bytes cannot replace the saved artifact", async () => {
  const turn = start(async (_backend, input) => {
    await writeFile(path.join(input.projectDir, "index.html"), Uint8Array.from([255]));
    interruptUserTurn(sessionId);
    return { exitCode: 1 };
  });
  await turn.promise;
  expect((await inspectCanonicalTree(projectDir)).tree_digest).toBe(digest);
  expect(getSqlite().query("SELECT status FROM artifact_operations WHERE id=?").get(turn.operationId)).toEqual({ status: "failed" });
});

test("Given a pending permission When decided twice Then one durable decision and a coherent snapshot are exposed", async () => {
  await insertNormalizedEvent(sessionId, { id: crypto.randomUUID(), ts: Date.now(), type: "tool.permission_required", turnId: "permission-turn", toolCallId: "permission", tool: "Bash", input: {} });
  const request = () => sessionRoutes.request(`/api/sessions/${sessionId}/tool-decision`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ toolCallId: "permission", decision: "allow" }) });
  expect((await request()).status).toBe(200);
  expect((await request()).status).toBe(409);
  const response = await sessionRoutes.request(`/api/sessions/${sessionId}/snapshot`);
  const body = await response.json();
  expect(body.data.pending_permissions).toEqual([]);
  expect(body.data.session.id).toBe(sessionId);
  expect(getSqlite().query("SELECT COUNT(*) value FROM events WHERE session_id=? AND type='tool.permission_decided'").get(sessionId)).toEqual({ value: 1 });
});

test("Given a real child tree continuously writing When its output callback fails Then the owned tree exits before failure returns", async () => {
  const script = `const child=Bun.spawn([process.execPath,'-e','setInterval(()=>{},1000)'],{stdin:'ignore',stdout:'ignore',stderr:'ignore'}); console.log(child.pid); setInterval(()=>process.stdout.write('x'.repeat(65536)),1);`;
  const owned = spawnOwnedProcess({ cmd: [process.execPath, "-e", script], stdin: "ignore", stdout: "pipe", stderr: "pipe" });
  const proc = owned.proc;
  let childPid = 0;
  const stdout = (async () => {
    const reader = proc.stdout.getReader();
    let text = "";
    try {
      while (!text.includes("\n")) {
        const part = await reader.read();
        if (part.done) throw new Error("fixture exited early");
        text += new TextDecoder().decode(part.value);
      }
      childPid = Number(text.split("\n")[0]);
      throw new Error("injected event persistence failure");
    } finally { reader.releaseLock(); }
  })();
  const stderr = new Response(proc.stderr).text().then(() => {});
  try {
    await expect(settleProcessStreams(owned, [stdout, stderr])).rejects.toThrow("injected event persistence failure");
    expect(Number.isSafeInteger(childPid) && childPid > 0).toBe(true);
    expect(() => process.kill(proc.pid, 0)).toThrow();
    expect(() => process.kill(childPid, 0)).toThrow();
  } finally {
    await closeOwnedProcess(owned, { timeoutMs: 3_000 });
    if (childPid > 0) { try { process.kill(childPid, "SIGKILL"); } catch {} }
  }
}, 15_000);
