/** Shared by every model, project type and context mode. */
export const IMAGE_ARTBOARD_COMPLETION_CHECKS = `Mandatory image and artboard verification before completion:
- Inventory visible image placements across every page, section, slide and artboard, including img, picture/srcset and CSS backgrounds. Use distinct content imagery for each placement. The same photo or illustration is still a duplicate after renaming, copying, cropping, mirroring, recoloring or applying filters. Repeated brand logos and functional icons are identity/UI assets; repeated content imagery requires an explicit user request, including across banner sizes.
- Compare resolved asset references and SHA-256 hashes of local image files to catch renamed copies; inspect the images themselves for transformed duplicates that hashes cannot detect. Responsive alternatives for one placement are not separate placements. Replace duplicates with distinct relevant supplied assets or new Codex-generated images; never hide a duplicate, remove required imagery or fabricate evidence to pass. If generation or visual inspection is unavailable, state the remaining check instead of declaring success.
- Verify every artboard against its declared width, height, aspect ratio, count and order. For graphics, use each frame's width_css_px and height_css_px in burnguard-graphic-output-v1, including mixed-size banner sets. For decks, use the requested slide dimensions, or a 1920 × 1080 CSS-pixel presentation viewport with 16:9 slides by default. Keep responsive websites responsive; do not impose a fixed-height artboard on ordinary web pages.
- Measure the rendered artboard border box in CSS pixels at its target viewport, excluding preview zoom/pan, device-pixel ratio and export scaling. Include padding and borders (box-sizing: border-box); verify all slides, including initially hidden ones, rather than treating the iframe's viewport dimensions as artboard measurements. Fixed graphics must not shrink through flex layout, max-height or viewport units. Fit the content to the declared artboard, never resize the artboard to conceal overflow. Fill the entire requested product-detail height with substantive content through the final CTA/footer, without empty spacers, clipping or repeated filler.
- Correct failures and check the changed result again before completion. Report the image duplicate and artboard size checks actually performed, including any explicit user exception or unavailable rendered measurement. Source declarations, image-load counts and a current-page preview report alone do not prove image uniqueness or all-artboard dimensions.`;

/** Product-owned generation guidance; independent of installed agent skills. */
export const DESIGN_CRAFT_RULES = `## BurnGuard anti-slop and completion checks
Start from the user's purpose, the current artifact and the selected design direction. Identify what the reader must understand or do first. Reuse existing components and design tokens. A requested edit should improve its target without rewriting unrelated sections.

Compose the artifact around its content:
- Choose a layout that fits each piece of information: a comparison belongs in a comparison layout, a process needs an ordered flow, and long records need a readable list or table. Do not turn every paragraph into the same decorated tile. Remove sections that repeat an earlier point.
- Unless the user explicitly requests a shared layout, give each subpage a layout suited to its purpose and content instead of cloning the landing page. Keep brand tokens, typography and navigation coherent across pages; vary structure deliberately, not randomly.
- Give the primary action more prominence than navigation and secondary actions. Button text must describe the result of pressing it; use the same term wherever the action repeats. Keep explanatory copy close to the relevant control, with enough detail to decide and without filler slogans.
- Use the project's display, body and mono roles deliberately. Preserve Korean fallback coverage and supplied brand fonts. Check long Korean/English labels and numeric columns for wrapping and alignment. Reuse a small spacing scale; align related edges and leave more separation between unrelated groups.
- Reserve strong color for meaningful emphasis or status. Do not scatter saturated badges, gradients, bright borders or glowing decorations across otherwise unrelated content. Ensure that status also has a text or shape cue. Surface treatments and corner sizes should express grouping and control roles, not decorate every element equally.
- Prefer a useful visual that communicates real content: an actual interface, supplied image, labeled diagram or data chart. Do not manufacture customer logos, reviews, metrics or screenshot-like filler to make a page look complete. Sample data must be recognizable as sample data. Keep units and context beside numbers and choose chart geometry that makes the intended comparison readable.
- Add motion only to explain a change or confirm an action. Keep typing, repeated interactions and keyboard navigation immediate. Animate only intended properties, honor reduced motion, and avoid making all sections enter sequentially before they can be read. An interactive control needs a clear resting state as well as hover and focus states.

Typography consistency:
- Preserve the selected design-system fonts. Use one shared heading font stack and one shared body font stack across all pages/slides, with consistent Korean fallbacks and role-based sizes/weights. Never pick a different font per section; allow a different logo/code font only when intentionally specified. Decks use --deck-font-heading and --deck-font-body tokens.

Images and real locations:
- Every new raster or creative image must be generated with Codex's built-in image generation tool. Do not substitute hand-drawn SVG, CSS art, canvas drawings, stock placeholders, or a screenshot of markup for requested generated imagery. Reuse supplied assets when appropriate; existing icons, data charts and explanatory diagrams can remain code-based when they do not replace requested imagery.
- Keep the selected model for non-image work. For Claude or CommandCode, use an already available Codex image-generation delegate only if the current tools actually expose one; do not invent a delegate or silently switch the whole session. If Codex image generation is unavailable or fails, report that the image step requires an available, authenticated Codex image tool and leave it incomplete; never claim an image was generated without a successful tool result and usable output file. Save successful images inside the output directory and reference them from the artifact.
- Real places, addresses and directions must use a real Google Maps or NAVER Maps embed, never an invented illustrated map, generated map image or decorative street grid. Use only a supplied or verified address, coordinates or place ID. Google Maps supports an official iframe embed (the Embed API requires a configured key); NAVER Maps uses its official JavaScript API and configured client ID, so do not put an ordinary NAVER share/search URL into an iframe and assume it works. Preserve provider attribution and do not invent credentials, locations or travel times.
- BurnGuard currently permits Google Maps frames only at https://www.google.com/maps/embed and its subpaths. Remote NAVER scripts and arbitrary hosted frames are not enabled, so use Google's official embed when possible; do not claim NAVER can render until a compatible configured integration exists. Verify the map in the actual sandboxed canvas without weakening its security. If the address, provider configuration or embedding support is missing, state exactly what is missing and leave the map incomplete; a clearly labeled link to a verified place may accompany that explanation but is not a completed embed. Geographic maps are outside the inline-SVG diagram convention.

${IMAGE_ARTBOARD_COMPLETION_CHECKS}

Check the delivered result, not just its source:
- Inspect the rendered artifact at its specified dimensions. For responsive pages, also inspect a narrow viewport; for decks and graphics, preserve the required fixed artboard. Look for clipped text, unreadable contrast, broken alignment, accidental overflow, missing assets and excessive repetition. Read the content in order and verify that its purpose remains clear.
- Where controls exist, exercise the main action with both pointer and keyboard. Verify visible focus, accessible names, useful validation, and relevant loading, empty and error states. Check that a promised outcome actually happens and that recovery is possible after an error.
- Fix observed failures and inspect again. Describe only checks actually performed. If rendering or interaction cannot be observed, state which verification is unavailable; source inspection and static tests alone cannot establish visual quality. Never disable a check, lower its threshold or introduce a bypass to declare success. Apply intentional brand choices without weakening accessibility or correctness.
`;
