#!/usr/bin/env bun
/**
 * OS-matrix coverage guard. A test file that no list in os-tests.yml names only ever runs on Linux, which is how
 * the suites added by PRs #178 and #190 missed macOS and Windows. Every test file must be named by an os-tests.yml
 * step or by the baseline of suites not yet covered; the baseline may only shrink.
 *
 *   bun scripts/qa/check-os-matrix-coverage.ts [--base-ref <git ref>]   check (exit 1 on any problem); with a base
 *                                                                       ref the baseline may not have grown since
 *                                                                       the merge base of HEAD and that ref
 *   bun scripts/qa/check-os-matrix-coverage.ts --write-baseline         regenerate the baseline
 */
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { BASELINE_EXCLUSIONS, planBaselineSuites } from "./baseline-suites";

export const OS_WORKFLOW = ".github/workflows/os-tests.yml";
export const UBUNTU_WORKFLOW = ".github/workflows/security.yml";
export const BASELINE_PATH = "scripts/qa/os-matrix-baseline.txt";
const TEST_ROOTS = ["packages", "scripts"] as const;
const TEST_FILE = /\.test\.[cm]?[jt]sx?$/;
const SKIPPED_SEGMENTS = new Set(["node_modules", "dist"]);
const BASELINE_HEADER = [
  "# Test files that no step in .github/workflows/os-tests.yml runs yet: they run on Ubuntu only, never on macOS or Windows.",
  "# On Ubuntu, scripts/qa/run-baseline-suites.ts runs them (security.yml), minus the exclusions listed with reasons in",
  "# scripts/qa/baseline-suites.ts; the coverage guard fails on an entry that is neither run nor excluded.",
  "# Entries may only be REMOVED: add the suite to os-tests.yml and delete its line here.",
  "# A new test file never goes here; it goes into os-tests.yml and security.yml.",
  "# Generated by: bun scripts/qa/check-os-matrix-coverage.ts --write-baseline",
];

export type CoverageProblemCode = "not_in_os_matrix" | "baseline_file_missing" | "baseline_entry_covered" | "baseline_not_sorted" | "baseline_grew" | "listed_file_missing" | "baseline_not_run" | "exclusion_not_in_baseline" | "exclusion_without_reason";
export type CoverageProblem = { readonly code: CoverageProblemCode; readonly path: string; readonly source: string };
export type GitRunner = (args: readonly string[]) => { readonly exitCode: number; readonly stdout: string };
export type CoverageInput = {
  readonly testFiles: readonly string[];
  readonly osListed: readonly string[];
  readonly ubuntuListed: readonly string[];
  readonly baseline: readonly string[];
  readonly previousBaseline: readonly string[] | null;
  readonly exists: (repoPath: string) => boolean;
  /** Reasons by path for the baseline suites the Ubuntu baseline step leaves out; omit to skip the baseline-run checks. */
  readonly exclusions?: Readonly<Record<string, string>>;
  /** Whether security.yml has a step that runs scripts/qa/run-baseline-suites.ts. */
  readonly ubuntuRunsBaseline?: boolean;
};

export const BASELINE_RUNNER = "scripts/qa/run-baseline-suites.ts";

/** True when any step of the workflow runs the baseline runner script. */
export function runsBaselineSuites(workflowYaml: string): boolean {
  const workflow: unknown = Bun.YAML.parse(workflowYaml);
  if (!isRecord(workflow) || !isRecord(workflow.jobs)) return false;
  return Object.values(workflow.jobs).some((job) => isRecord(job) && Array.isArray(job.steps)
    && job.steps.some((step) => isRecord(step) && typeof step.run === "string" && step.run.includes(BASELINE_RUNNER)));
}

/** One spelling per file: forward slashes, no quotes, no leading "./", so a Windows-style entry names the same file. */
export function normalizeTestPath(spelling: string): string {
  return spelling.trim().replace(/^["']+|["']+$/g, "").replaceAll("\\", "/").replace(/\/{2,}/g, "/").replace(/^(?:\.\/)+/, "");
}

const byCodeUnit = (left: string, right: string): number => left < right ? -1 : left > right ? 1 : 0;
const sortedUnique = (paths: readonly string[]): string[] => [...new Set(paths)].sort(byCodeUnit);
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);

/** Every test file named by a `run` command of any step in the workflow, in file order. */
export function listedTestPaths(workflowYaml: string): string[] {
  const workflow: unknown = Bun.YAML.parse(workflowYaml);
  if (!isRecord(workflow) || !isRecord(workflow.jobs)) throw new TypeError("workflow has no jobs");
  const listed: string[] = [];
  for (const job of Object.values(workflow.jobs)) {
    if (!isRecord(job) || !Array.isArray(job.steps)) continue;
    for (const step of job.steps) {
      if (!isRecord(step) || typeof step.run !== "string") continue;
      for (const token of step.run.split(/\s+/)) {
        const candidate = normalizeTestPath(token);
        if (TEST_FILE.test(candidate)) listed.push(candidate);
      }
    }
  }
  return listed;
}

export function parseBaseline(text: string): string[] {
  return text.split(/\r?\n/).map((line) => line.trim()).filter((line) => line !== "" && !line.startsWith("#")).map(normalizeTestPath);
}

export function formatBaseline(paths: readonly string[]): string {
  return [...BASELINE_HEADER, ...sortedUnique(paths.map(normalizeTestPath))].join("\n") + "\n";
}

export function uncoveredTestFiles(testFiles: readonly string[], osListed: readonly string[]): string[] {
  const covered = new Set(osListed.map(normalizeTestPath));
  return sortedUnique(testFiles.map(normalizeTestPath)).filter((file) => !covered.has(file));
}

export function checkCoverage(input: CoverageInput): CoverageProblem[] {
  const testFiles = sortedUnique(input.testFiles.map(normalizeTestPath));
  const osListed = new Set(input.osListed.map(normalizeTestPath));
  const baseline = input.baseline.map(normalizeTestPath);
  const baselined = new Set(baseline);
  const present = new Set(testFiles);
  const problems: CoverageProblem[] = [];
  for (const [source, listed] of [[OS_WORKFLOW, [...osListed]], [UBUNTU_WORKFLOW, sortedUnique(input.ubuntuListed.map(normalizeTestPath))]] as const) {
    for (const file of listed) if (!input.exists(file)) problems.push({ code: "listed_file_missing", path: file, source });
  }
  for (const file of testFiles) if (!osListed.has(file) && !baselined.has(file)) problems.push({ code: "not_in_os_matrix", path: file, source: OS_WORKFLOW });
  for (const file of sortedUnique(baseline)) {
    if (osListed.has(file)) problems.push({ code: "baseline_entry_covered", path: file, source: BASELINE_PATH });
    else if (!present.has(file)) problems.push({ code: "baseline_file_missing", path: file, source: BASELINE_PATH });
  }
  if (baseline.join("\n") !== sortedUnique(baseline).join("\n")) problems.push({ code: "baseline_not_sorted", path: BASELINE_PATH, source: BASELINE_PATH });
  if (input.exclusions !== undefined && input.ubuntuRunsBaseline !== undefined) {
    for (const [file, reason] of Object.entries(input.exclusions)) {
      const normalized = normalizeTestPath(file);
      if (reason.trim() === "") problems.push({ code: "exclusion_without_reason", path: normalized, source: BASELINE_RUNNER });
      if (!baselined.has(normalized)) problems.push({ code: "exclusion_not_in_baseline", path: normalized, source: BASELINE_RUNNER });
    }
    const exclusions = Object.fromEntries(Object.entries(input.exclusions).map(([file, reason]) => [normalizeTestPath(file), reason]));
    const plan = planBaselineSuites(sortedUnique(baseline), input.ubuntuListed.map(normalizeTestPath), exclusions);
    const handled = new Set([...(input.ubuntuRunsBaseline ? plan.run : []), ...plan.listed, ...plan.excluded]);
    for (const file of sortedUnique(baseline)) if (!handled.has(file)) problems.push({ code: "baseline_not_run", path: file, source: UBUNTU_WORKFLOW });
  }
  if (input.previousBaseline !== null) {
    const previous = new Set(input.previousBaseline.map(normalizeTestPath));
    for (const file of sortedUnique(baseline)) if (!previous.has(file)) problems.push({ code: "baseline_grew", path: file, source: BASELINE_PATH });
  }
  return problems;
}

export async function discoverTestFiles(root: string): Promise<string[]> {
  const found: string[] = [];
  for (const base of TEST_ROOTS) {
    if (!existsSync(path.join(root, base))) continue;
    for await (const file of new Bun.Glob("**/*.test.*").scan({ cwd: path.join(root, base), onlyFiles: true })) {
      const repoPath = normalizeTestPath(`${base}/${file}`);
      if (TEST_FILE.test(repoPath) && !repoPath.split("/").some((segment) => SKIPPED_SEGMENTS.has(segment))) found.push(repoPath);
    }
  }
  return sortedUnique(found);
}

export type CoverageReport = { readonly problems: readonly CoverageProblem[]; readonly testFiles: number; readonly inOsMatrix: number; readonly baselined: number };

async function readRepo(root: string): Promise<{ testFiles: string[]; osListed: string[]; ubuntuListed: string[]; ubuntuRunsBaseline: boolean }> {
  const [testFiles, os, ubuntu] = await Promise.all([discoverTestFiles(root), readFile(path.join(root, OS_WORKFLOW), "utf8"), readFile(path.join(root, UBUNTU_WORKFLOW), "utf8")]);
  return { testFiles, osListed: listedTestPaths(os), ubuntuListed: listedTestPaths(ubuntu), ubuntuRunsBaseline: runsBaselineSuites(ubuntu) };
}

/** `exclusions` null skips the baseline-run checks (a repository without the baseline runner). */
export async function checkRepository(root: string, previousBaseline: readonly string[] | null = null, exclusions: Readonly<Record<string, string>> | null = BASELINE_EXCLUSIONS): Promise<CoverageReport> {
  const repo = await readRepo(root);
  const baselineFile = path.join(root, BASELINE_PATH);
  const baseline = existsSync(baselineFile) ? parseBaseline(await readFile(baselineFile, "utf8")) : [];
  const problems = checkCoverage({ ...repo, baseline, previousBaseline, ...(exclusions === null ? {} : { exclusions }), exists: (repoPath) => existsSync(path.join(root, repoPath)) });
  const covered = new Set(repo.osListed);
  return { problems, testFiles: repo.testFiles.length, inOsMatrix: repo.testFiles.filter((file) => covered.has(file)).length, baselined: baseline.length };
}

export async function writeBaseline(root: string): Promise<number> {
  const repo = await readRepo(root);
  const uncovered = uncoveredTestFiles(repo.testFiles, repo.osListed);
  await writeFile(path.join(root, BASELINE_PATH), formatBaseline(uncovered));
  return uncovered.length;
}

const HELP: Record<CoverageProblemCode, string> = {
  not_in_os_matrix: "test file runs on no macOS or Windows job: add it to a list in os-tests.yml (and security.yml for Ubuntu)",
  baseline_file_missing: "baseline names a file that no longer exists: delete the line",
  baseline_entry_covered: "baseline names a file that os-tests.yml already runs: delete the line",
  baseline_not_sorted: "baseline is not sorted or has duplicates: rerun with --write-baseline and keep only removals",
  baseline_grew: "baseline gained an entry since the merge base: a test file must be added to os-tests.yml, never to the baseline",
  listed_file_missing: "workflow lists a test file that does not exist",
  baseline_not_run: "baseline suite is neither run by the Ubuntu baseline step (security.yml must run scripts/qa/run-baseline-suites.ts) nor excluded with a reason in scripts/qa/baseline-suites.ts",
  exclusion_not_in_baseline: "scripts/qa/baseline-suites.ts excludes a file that is not in the baseline: delete the exclusion",
  exclusion_without_reason: "scripts/qa/baseline-suites.ts excludes a suite without a reason",
};

/**
 * The baseline at the merge base of HEAD and the ref, or null when that commit has none. The merge base, not the
 * ref's tip: a branch that is behind a main which already removed entries has not grown the baseline.
 */
export function baselineAtMergeBase(ref: string, git: GitRunner): readonly string[] | null {
  const mergeBase = git(["merge-base", "HEAD", ref]);
  const base = mergeBase.stdout.trim();
  if (mergeBase.exitCode !== 0 || base === "") throw new TypeError("base ref has no merge base with HEAD in this checkout");
  if (git(["cat-file", "-e", `${base}:${BASELINE_PATH}`]).exitCode !== 0) return null;
  return parseBaseline(git(["show", `${base}:${BASELINE_PATH}`]).stdout);
}

function gitIn(root: string): GitRunner {
  return (args) => {
    const result = Bun.spawnSync({ cmd: ["git", ...args], cwd: root, stdout: "pipe", stderr: "ignore" });
    return { exitCode: result.exitCode, stdout: new TextDecoder().decode(result.stdout) };
  };
}

if (import.meta.main) {
  const root = path.resolve(import.meta.dir, "..", "..");
  const args = process.argv.slice(2);
  if (args.includes("--write-baseline")) {
    console.log(`os-matrix coverage: baseline written with ${await writeBaseline(root)} entries`);
    process.exit(0);
  }
  const refIndex = args.indexOf("--base-ref");
  const ref = refIndex === -1 ? undefined : args[refIndex + 1];
  if (refIndex !== -1 && (ref === undefined || ref === "")) { console.error("os-matrix coverage: --base-ref needs a git ref"); process.exit(2); }
  let previousBaseline: readonly string[] | null = null;
  try { if (ref !== undefined) previousBaseline = baselineAtMergeBase(ref, gitIn(root)); }
  catch (error) { console.error(`os-matrix coverage: ${error instanceof Error ? error.message : String(error)}`); process.exit(2); }
  const report = await checkRepository(root, previousBaseline);
  for (const problem of report.problems) console.error(`${problem.code}\t${problem.path}\t(${problem.source}) ${HELP[problem.code]}`);
  console.log(`os-matrix coverage: ${report.testFiles} test files, ${report.inOsMatrix} in the OS matrix, ${report.baselined} in the baseline, ${report.problems.length} problems`);
  process.exit(report.problems.length === 0 ? 0 : 1);
}
