/** Reference-derived page regions. Geometry and all paint remain owned by each theme's tokens. */
type RegionTheme = {
  name: string;
  archetype: "marketing" | "article" | "shop" | "poster" | "workspace" | "place";
  token: (name: string, fallback?: string) => string;
};

const CONTENT = {
  marketing: ["만드는 일에 집중하세요", "아이디어를 정리하고, 다음 시도를 더 가볍게 시작하는 작업 공간입니다.", "제품 둘러보기", "제품", "작업", "시작하기"],
  article: ["오래 들여다볼수록 보이는 것들", "한 번의 결론보다 오래 남는 질문을 모읍니다. 오늘의 관찰을 다음 이야기로 이어갑니다.", "이번 호 읽기", "이야기", "지난 호", "편집실"],
  shop: ["계절이 지나도 남는 것들", "매일 손이 가는 소재와 오래 쓰이는 형태. 천천히 고른 물건을 소개합니다.", "컬렉션 보기", "컬렉션", "소재", "이용 안내"],
  poster: ["흐린 날의 긴 산책", "봄의 저녁, 함께 보고 오래 이야기할 작품을 만납니다. 작은 극장에서 시작되는 새로운 장면.", "프로그램 보기", "프로그램", "참여자", "방문 안내"],
  workspace: ["복잡한 흐름을 한눈에", "흩어진 기록을 연결하고 지금 필요한 신호를 찾아보세요. 일의 다음 단계가 분명해집니다.", "기록 살펴보기", "개요", "운영 기록", "도움말"],
  place: ["하루의 속도가 달라지는 곳", "빛이 머무는 방과 계절을 닮은 재료. 잠시 멈춰 주변을 돌아볼 수 있는 공간입니다.", "공간 둘러보기", "공간", "프로그램", "찾아오기"],
} as const;

const html = (value: string) => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
const brand = (theme: RegionTheme) => html(theme.name.replace(/(?: Built-in)? Theme$/, ""));
const links = (theme: RegionTheme) => ["overview", "collection", "contact"].map((id, i) => `<a href="#${id}">${CONTENT[theme.archetype][i + 3]}</a>`).join("");
const menu = (body: string, label = "메뉴") => `<details class="region-menu"><summary>${label}<span aria-hidden="true"> ＋</span></summary><div class="region-menu-panel">${body}</div></details>`;

export function navigationFor(theme: RegionTheme): string {
  const mark = `<a class="region-brand" href="#overview">${brand(theme)}</a>`;
  const entries = links(theme);
  const groups = ["둘러보기", "더 알아보기", "함께하기"].map(label => `<div class="region-nav-group"><b>${label}</b>${entries}</div>`).join("");
  const patterns: Record<string, string> = {
    "floating-island": `${mark}<nav class="region-nav-links">${entries}</nav>${menu(entries)}`,
    "mega-feature": `${mark}<nav class="region-nav-numbered">${["overview", "collection", "contact"].map((id, i) => `<a href="#${id}"><small>0${i + 1}</small>${CONTENT[theme.archetype][i + 3]}</a>`).join("")}</nav>${menu(`<p class="region-menu-intro">오늘의 선택에서<br>새로운 가능성까지.</p>${groups}`, "전체 보기")}`,
    "icon-taxonomy": `${mark}<nav class="region-nav-chips">${["overview", "collection", "contact"].map((id, i) => `<a href="#${id}"><span aria-hidden="true">${["◈", "▤", "◎"][i]}</span>${CONTENT[theme.archetype][i + 3]}</a>`).join("")}</nav>${menu(groups, "탐색")}`,
    "enterprise-columns": `<div class="region-utility"><span>한곳에서 연결되는 모든 작업</span><a href="#contact">도움말 ↗</a></div><div class="region-nav-main">${mark}<nav class="region-nav-links">${entries}</nav>${menu(groups, "전체 서비스")}</div>`,
    "segmented-pill": `${mark}<nav class="region-nav-segments">${entries}</nav>${menu(`<div class="region-menu-index">${groups}</div>`, "더 보기")}`,
    "side-rail": `${mark}<p class="region-rail-note">Independent ideas.<br>Everyday work.</p><nav class="region-nav-vertical">${entries}</nav><a class="region-rail-cta" href="#contact">새로운 이야기 ↗</a>`,
    "profile-popover": `${mark}<div class="region-profile-links"><a href="#collection">작업</a><a href="#contact">안내</a></div>${menu(`<div class="region-profile-avatar" aria-hidden="true">${brand(theme).slice(0, 1)}</div><b>${brand(theme)}</b><p>작은 관찰에서 시작되는 새로운 일.</p>${entries}`, "소개")}`,
    "editorial-overlay": `${mark}<a class="region-feature-link" href="#collection"><small>SELECTED / 01</small>${CONTENT[theme.archetype][4]} ↗</a>${menu(`<div class="region-overlay-feature">지금 주목하는<br>새로운 장면</div><nav>${entries}</nav><p>이야기는 이곳에서 이어집니다.</p>`, "둘러보기")}`,
  };
  const pattern = theme.token("layout-nav-pattern");
  if (!patterns[pattern]) throw new Error(`Unknown navigation pattern: ${pattern}`);
  return `<a class="region-skip" href="#main-content">본문으로 바로가기</a><header class="region-nav" data-nav-pattern="${pattern}" data-nav-position="${theme.token("layout-nav-position", "top")}" aria-label="주 메뉴">${patterns[pattern]}</header>`;
}

export function heroFor(theme: RegionTheme, media: string): string {
  const [title, description, action] = CONTENT[theme.archetype];
  const copy = `<div class="region-copy"><p class="eyebrow">${brand(theme)} / ${theme.archetype.toUpperCase()}</p><h1>${title}</h1><p class="region-lede">${description}</p><a class="btn" href="#collection">${action} ↗</a></div>`;
  const visual = (extra = "") => `<div class="region-visual ${extra}">${media}</div>`;
  const label = `<div class="region-caption"><span>새롭게 바라보는 매일</span><span>01 / 2026</span></div>`;
  const patterns: Record<string, string> = {
    "split-left": `${copy}${visual()}`,
    "centered-form": `${copy}<div class="region-action-card"><span class="tag">처음 오셨나요?</span>${menu(`<p>관심 있는 내용을 골라 둘러보세요.</p>${links(theme)}`, "어디부터 시작할까요?")}</div>${visual()}`,
    "media-bottom": `${copy}<p class="region-side-note">우리의 다음 이야기는<br>지금 이곳에서 시작됩니다.</p>${visual()}${label}`,
    "masthead-crop": `<p class="region-masthead" aria-hidden="true">${brand(theme)}</p>${copy}${visual()}${label}`,
    "product-panel": `${copy}<div class="region-visual region-product-panel"><div class="region-window-bar"><span>● ● ●</span><span>${brand(theme)} / WORKSPACE</span></div>${media}<div class="region-product-status"><span>오늘의 기록 <b>24</b></span><span>진행 중 <b>08</b></span><span>완료 <b>16</b></span></div></div>`,
    "specimen-poster": `<div class="region-specimen-index" aria-hidden="true">01<span>SPRING<br>EDITION</span></div>${copy}${visual()}<div class="region-specimen-stamp">새로운 시선<br>새로운 장면<br>2026</div>`,
    "split-reverse": `${visual()}${copy}<div class="region-side-note">작은 차이에서 시작되는<br>조금 더 나은 하루.</div>`,
    "filmstrip": `<div class="region-film-index">FRAME 001—024</div>${visual("region-film")}${copy}${label}`,
    "framed-cover": `<div class="region-cover-label">${brand(theme)} · SELECTED STORIES</div>${copy}${visual()}${label}`,
    "portfolio-peek": `<div class="region-portfolio-role">관찰하고<br>기록하고<br>다시 만듭니다.</div>${copy}${visual()}<a class="region-portfolio-next" href="#collection">선택한 작업 ↓</a>`,
    "type-marquee": `<div class="region-ticker" aria-hidden="true"><span>IDEAS · PEOPLE · PLACES</span> · <span>${brand(theme)}</span></div>${copy}${visual()}${label}`,
    "fullbleed-top": `${visual()}${copy}<a class="region-cover-scroll" href="#collection">아래로 둘러보기 ↓</a>`,
  };
  const pattern = theme.token("layout-hero-pattern");
  if (!patterns[pattern]) throw new Error(`Unknown hero pattern: ${pattern}`);
  return `<section class="region-hero" id="overview" data-hero-pattern="${pattern}" data-media-position="${theme.token("layout-hero-media-position", "right")}"><div class="region-stage">${patterns[pattern]}</div></section>`;
}

export function footerFor(theme: RegionTheme, media: string): string {
  const mark = `<a class="region-footer-brand" href="#overview">${brand(theme)}</a>`;
  const legal = `<div class="region-legal"><span>© 2026 ${brand(theme)}</span><a href="#overview">맨 위로 ↑</a></div>`;
  const columns = Number(theme.token("layout-footer-columns", "3"));
  if (!Number.isInteger(columns) || columns < 1 || columns > 6) throw new Error("Invalid footer column count");
  const groups = Array.from({ length: columns }, (_, i) => `<div class="region-footer-group"><h3>${["둘러보기", "이용 안내", "이야기", "연결", "프로그램", "자료실"][i]}</h3>${links(theme)}</div>`).join("");
  const grid = `<nav class="region-footer-grid" aria-label="하단 메뉴">${groups}</nav>`;
  const cta = `<div class="region-footer-cta"><h2>다음 이야기를<br>함께 시작해요.</h2><a class="btn" href="#overview">처음부터 둘러보기 ↗</a></div>`;
  const patterns: Record<string, string> = {
    "ruled-community": `<div class="region-ruled-cells">${mark}${cta}${grid}</div>${legal}<div class="region-community-band" aria-hidden="true">○ ＋ ◇ ○ ＋ ◇</div>`,
    "window-stage": `<div class="region-stage-title">새로운 연결</div><div class="region-footer-windows"><div class="region-footer-window"><span>EXPLORE ↗</span>${grid}</div><div class="region-footer-window">${cta}</div></div><div class="region-footer-ticker">${brand(theme)} · KEEP IN TOUCH · ${brand(theme)}</div>${legal}`,
    "studio-address": `<div class="region-studio-top">${mark}${grid}</div><div class="region-address-row"><div><span class="eyebrow">STUDIO 01</span><p>작업을 나누는 곳<br>평일 10:00–18:00</p></div><div><span class="eyebrow">STUDIO 02</span><p>이야기가 이어지는 곳<br>방문 전 안내 확인</p></div><a href="#collection">선택한 작업 ↗</a></div>${legal}`,
    "photo-strip": `<div class="region-photo-top">${mark}${grid}</div><div class="region-footer-photo">${media}</div>${legal}`,
    "centered-cta": `${cta}<nav class="region-footer-center-links" aria-label="하단 메뉴">${links(theme)}</nav><div class="region-footer-watermark">${brand(theme)}</div>${legal}`,
    "scenic-overlay": `<div class="region-footer-scene">${media}<div class="region-scenic-content">${cta}${grid}</div></div>${legal}`,
    "contact-ledger": `<div class="region-contact-ledger">${mark}<div><p class="eyebrow">LET'S KEEP IN TOUCH</p><p>새로운 소식과 다음 일정을<br>이곳에서 만나보세요.</p><a class="region-news-rule" href="#collection">최근 이야기 보기 ↗</a></div>${grid}</div>${legal}`,
    "retail-accordion": `<div class="region-retail-top">${cta}<nav class="region-retail-groups" aria-label="하단 메뉴">${Array.from({ length: columns }, (_, i) => `<details open><summary>${["컬렉션", "고객 안내", "브랜드", "자료실", "소식", "연결"][i]}</summary><div>${links(theme)}</div></details>`).join("")}</nav></div><div class="region-retail-locale"><span>대한민국 · 한국어</span><a href="#contact">이용 안내</a></div>${mark}${legal}`,
  };
  const pattern = theme.token("layout-footer-pattern");
  if (!patterns[pattern]) throw new Error(`Unknown footer pattern: ${pattern}`);
  return `<footer class="region-footer" id="contact" data-footer-pattern="${pattern}">${patterns[pattern]}</footer>`;
}

export function regionCss(theme: RegionTheme): string {
  const navWidth = theme.token("layout-nav-width", "0px");
  return `
body{position:relative;overflow-wrap:anywhere}
#main-content,#collection{min-width:0}a:focus-visible,summary:focus-visible{outline:3px solid var(--primary-blue);outline-offset:4px}
.region-skip{position:absolute;left:var(--sp-4);top:0;transform:translateY(-120%);z-index:20;background:var(--surface);padding:var(--sp-3)}.region-skip:focus{transform:none}
.region-nav{position:relative;z-index:5;display:flex;align-items:center;justify-content:space-between;gap:var(--sp-5);min-height:var(--layout-nav-height,var(--layout-nav-h,72px));max-width:${navWidth === "0px" || navWidth === "0" ? "var(--layout-max)" : "min(var(--layout-max),var(--layout-nav-width))"};margin-inline:auto;padding:var(--sp-3) var(--layout-margin);border-bottom:1px solid var(--border);background:var(--bg);width:100%;font-size:var(--fs-14)}
.region-brand{text-decoration:none;font-family:var(--font-display);font-size:var(--fs-20);line-height:1.15;font-weight:var(--fw-semibold);max-width:15ch}
.region-nav nav,.region-profile-links{display:flex;align-items:center;gap:var(--sp-5)}.region-nav a{text-decoration:none}.region-nav a:hover{text-decoration:underline;text-underline-offset:.3em}
.region-menu summary{cursor:pointer;list-style:none;white-space:nowrap}.region-menu summary::-webkit-details-marker{display:none}.region-menu summary::marker{content:""}
.region-menu-panel{position:absolute;top:100%;right:0;left:0;padding:var(--sp-8);background:var(--surface);border:1px solid var(--border);box-shadow:var(--shadow-3);display:flex;gap:var(--sp-8);flex-wrap:wrap;max-height:75vh;overflow:auto}.region-menu-panel a{display:block;padding-block:var(--sp-2)}.region-nav-group{flex:1;min-width:140px}.region-nav-group b{display:block;margin-bottom:var(--sp-3);font-family:var(--font-mono);font-size:var(--fs-12)}.region-menu-intro{font-size:var(--fs-24);margin:0;flex:1}
[data-nav-pattern="floating-island"]{margin-block:var(--sp-4);border:1px solid var(--border);border-radius:var(--r-pill);padding-inline:var(--sp-6);box-shadow:var(--shadow-1)}
[data-nav-pattern="mega-feature"]{align-items:stretch;padding-block:0}.region-nav-numbered{flex:1;justify-content:space-evenly;border-inline:1px solid var(--border)}.region-nav-numbered a{display:grid;gap:var(--sp-1);padding:var(--sp-4)}.region-nav-numbered small{font-family:var(--font-mono);color:var(--fg-3);font-size:var(--fs-12)}[data-nav-pattern="mega-feature"]>.region-brand,[data-nav-pattern="mega-feature"]>.region-menu{align-self:center}
.region-nav-chips a{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:var(--sp-2);padding:var(--sp-3);border-radius:var(--r-8);background:var(--bg-subtle)}.region-nav-chips span{font-size:var(--fs-24);color:var(--primary-blue)}
[data-nav-pattern="enterprise-columns"]{display:block;padding-top:0}.region-utility{display:flex;justify-content:space-between;gap:var(--sp-3);font-family:var(--font-mono);font-size:var(--fs-12);padding-block:var(--sp-2);border-bottom:1px solid var(--border);color:var(--fg-3)}.region-nav-main{display:flex;align-items:center;justify-content:space-between;gap:var(--sp-4);min-height:var(--layout-nav-height,var(--layout-nav-h,72px))}
.region-nav-segments{gap:0!important;border:1px solid var(--border);border-radius:var(--r-pill);overflow:hidden}.region-nav-segments a{padding:var(--sp-3) var(--sp-5);border-right:1px solid var(--border)}.region-nav-segments a:last-child{border:0}.region-nav-segments a:first-child{background:var(--bg-muted)}.region-menu-index{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--sp-8);width:100%}
[data-nav-pattern="side-rail"]{flex-direction:column;align-items:stretch;justify-content:flex-start;gap:var(--sp-10)}.region-rail-note{font-family:var(--font-mono);font-size:var(--fs-12);color:var(--fg-3)}.region-nav-vertical{flex-direction:column;align-items:stretch!important}.region-nav-vertical a{padding-block:var(--sp-4);border-bottom:1px solid var(--border);font-size:var(--fs-20)}.region-rail-cta{margin-top:auto;border:1px solid var(--border);padding:var(--sp-4)}
[data-nav-pattern="profile-popover"]{border:0}.region-profile-links{margin-left:auto}.region-profile-links a{border:1px solid var(--border);border-radius:var(--r-pill);padding:var(--sp-2) var(--sp-4)}[data-nav-pattern="profile-popover"] .region-menu{background:var(--bg-muted);border-radius:var(--r-pill);padding:var(--sp-2) var(--sp-4)}[data-nav-pattern="profile-popover"] .region-menu-panel{left:auto;width:min(340px,100%);display:block;border-radius:var(--r-8)}.region-profile-avatar{display:grid;place-items:center;width:64px;height:64px;border-radius:50%;background:var(--primary-blue);color:var(--fg-on-brand);font-family:var(--font-display);font-size:var(--fs-32);margin-bottom:var(--sp-4)}
.region-feature-link{margin-left:auto;display:grid;gap:var(--sp-1);font-family:var(--font-serif)}.region-feature-link small{font-family:var(--font-mono);font-size:var(--fs-12);color:var(--fg-3)}[data-nav-pattern="editorial-overlay"] .region-menu-panel{min-height:360px;display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr)}.region-overlay-feature{background:var(--bg-muted);padding:var(--sp-6);font-family:var(--font-display);font-size:var(--fs-32)}[data-nav-pattern="editorial-overlay"] .region-menu-panel nav{align-items:flex-start;flex-direction:column;font-size:var(--fs-32)}
body:has([data-nav-position="side"]){display:grid;grid-template-columns:var(--layout-nav-width,220px) minmax(0,1fr)}[data-nav-position="side"]{grid-column:1;grid-row:1 / 3;max-width:none;min-height:100vh;padding:var(--sp-6);border-right:1px solid var(--border);margin:0}[data-nav-position="side"]~main,[data-nav-position="side"]~footer{grid-column:2}
[data-nav-position="overlay"]{position:absolute;top:var(--sp-4);left:50%;transform:translateX(-50%);width:calc(100% - var(--layout-margin)*2)}body:has([data-nav-position="overlay"]) .region-stage{padding-top:calc(var(--layout-nav-height,var(--layout-nav-h,72px)) + var(--sp-10))}
[data-nav-position="bottom"]{position:fixed;bottom:var(--sp-4);left:50%;transform:translateX(-50%);width:calc(100% - var(--layout-margin)*2);border:1px solid var(--border);border-radius:var(--r-pill)}[data-nav-position="bottom"] .region-menu-panel{top:auto;bottom:100%}body:has([data-nav-position="bottom"]){padding-bottom:calc(var(--layout-nav-height,var(--layout-nav-h,72px)) + var(--sp-8))}
.region-hero{padding:var(--sp-8) var(--layout-margin) 0;max-width:var(--layout-max);margin-inline:auto}.region-stage{display:grid;grid-template-columns:minmax(0,var(--layout-hero-copy-ratio,45%)) minmax(0,1fr);gap:var(--layout-gutter);min-height:var(--layout-hero-min-height,520px);align-items:center;position:relative}.region-copy{min-width:0;position:relative;text-align:var(--layout-hero-align,start);z-index:1;padding-block:var(--sp-6)}.region-copy h1{font-family:var(--font-display);font-weight:var(--fw-medium);font-size:clamp(var(--fs-32),5.8cqi,var(--fs-80));line-height:var(--lh-display,var(--lh-tight));letter-spacing:var(--ls-display,var(--ls-tight));max-width:var(--layout-hero-title-measure,16ch);margin:var(--sp-5) 0;word-break:keep-all;overflow-wrap:anywhere}.region-lede{font-size:var(--fs-18);color:var(--fg-2);max-width:var(--layout-measure,54ch);margin-block:var(--sp-5) var(--sp-8)}.region-visual{min-width:0;overflow:hidden;aspect-ratio:var(--layout-hero-media-ratio,var(--layout-hero,16 / 10));margin-top:var(--layout-hero-offset,0px);background:var(--bg-muted);border-radius:var(--r-8)}.region-visual>.fig{width:100%;height:100%;object-fit:var(--family-media-fit,cover)}.region-caption{grid-column:1 / -1;display:flex;justify-content:space-between;gap:var(--sp-3);font-family:var(--font-mono);font-size:var(--fs-12);color:var(--fg-3);padding-block:var(--sp-3);border-bottom:1px solid var(--border)}.region-side-note{font-size:var(--fs-14);color:var(--fg-3);align-self:end;margin:0;padding-bottom:var(--sp-6)}
[data-media-position="left"] .region-stage{grid-template-columns:minmax(0,1fr) minmax(0,var(--layout-hero-copy-ratio,45%))}[data-media-position="left"] .region-copy{grid-column:2;grid-row:1}[data-media-position="left"] .region-visual{grid-column:1;grid-row:1}
[data-media-position="below"] .region-stage{grid-template-columns:1fr}[data-media-position="below"] .region-copy{max-width:var(--layout-hero-copy-ratio,70%);justify-self:var(--layout-hero-align,start)}[data-media-position="below"] .region-visual{grid-column:1 / -1}
[data-hero-pattern="centered-form"] .region-stage{grid-template-columns:1fr;justify-items:center;gap:var(--sp-5)}[data-hero-pattern="centered-form"] .region-copy{max-width:var(--layout-hero-copy-ratio,70%)}[data-hero-pattern="centered-form"] h1,[data-hero-pattern="centered-form"] .region-lede{margin-inline:auto}.region-action-card{position:relative;display:flex;align-items:center;gap:var(--sp-4);border:1px solid var(--border);background:var(--surface);padding:var(--sp-4);border-radius:var(--r-8);max-width:100%}.region-action-card .region-menu-panel{z-index:3;min-width:240px}.region-action-card .region-menu-panel p{margin:0}[data-hero-pattern="centered-form"] .region-visual{width:70%;}
[data-hero-pattern="media-bottom"] .region-stage{grid-template-columns:minmax(0,var(--layout-hero-copy-ratio,60%)) minmax(0,1fr)}[data-hero-pattern="media-bottom"] .region-copy{max-width:none}[data-hero-pattern="media-bottom"] .region-visual{grid-column:1 / -1}.region-masthead{grid-column:1 / -1;font-family:var(--font-display);font-size:clamp(var(--fs-48),10cqi,10rem);line-height:1;letter-spacing:var(--ls-tight);border-bottom:1px solid var(--border);padding-block:var(--sp-4);word-break:break-word}[data-hero-pattern="masthead-crop"] .region-visual{border-radius:0}[data-hero-pattern="masthead-crop"] .region-copy h1{font-size:clamp(var(--fs-32),4cqi,var(--fs-64))}
.region-product-panel{display:grid;grid-template-rows:auto minmax(0,1fr) auto;border:1px solid var(--border-strong);box-shadow:var(--shadow-3);transform:translateY(var(--layout-hero-offset,0px));margin-top:0}.region-product-panel>.fig{min-height:0}.region-window-bar,.region-product-status{display:flex;justify-content:space-between;gap:var(--sp-3);padding:var(--sp-3);background:var(--surface);font-family:var(--font-mono);font-size:var(--fs-12);border-bottom:1px solid var(--border)}.region-product-status{border-top:1px solid var(--border);border-bottom:0}.region-product-status b{display:block;font-size:var(--fs-20);font-weight:var(--fw-medium)}
[data-hero-pattern="specimen-poster"] .region-stage{border:var(--sp-3) solid var(--fg-1);padding:var(--sp-6);grid-template-columns:minmax(0,var(--layout-hero-copy-ratio,55%)) minmax(0,1fr)}.region-specimen-index{grid-column:1 / -1;display:flex;justify-content:space-between;align-items:center;font-family:var(--font-display);font-size:var(--fs-64);border-bottom:2px solid var(--border-strong)}.region-specimen-index span{font-family:var(--font-mono);font-size:var(--fs-14)}[data-hero-pattern="specimen-poster"] .region-copy h1{transform:rotate(var(--family-creative-type-rotation,0deg));font-size:clamp(var(--fs-32),5cqi,var(--fs-64))}.region-specimen-stamp{grid-column:1 / -1;justify-self:end;font-family:var(--font-mono);font-size:var(--fs-12);border:1px solid var(--fg-1);padding:var(--sp-3);transform:rotate(-5deg)}[data-hero-pattern="split-reverse"] .region-side-note{grid-column:1 / -1;border-top:1px solid var(--border);padding-top:var(--sp-4)}
[data-hero-pattern="filmstrip"] .region-stage{grid-template-columns:var(--sp-8) minmax(0,1fr);gap:var(--sp-4)}.region-film-index{writing-mode:vertical-rl;font-family:var(--font-mono);font-size:var(--fs-12);align-self:stretch;text-align:center;letter-spacing:.16em}[data-hero-pattern="filmstrip"] .region-visual{grid-column:2;grid-row:1;border-radius:0;border-block:var(--sp-5) dashed var(--fg-1)}[data-hero-pattern="filmstrip"] .region-copy{grid-column:2;grid-row:2;max-width:var(--layout-hero-copy-ratio,80%)}[data-hero-pattern="filmstrip"] h1{font-size:clamp(var(--fs-32),6vw,var(--fs-80))}
[data-hero-pattern="framed-cover"] .region-stage{border:1px solid var(--border-strong);padding:var(--sp-8);grid-template-columns:1fr}.region-cover-label{width:100%;font-family:var(--font-mono);font-size:var(--fs-12);letter-spacing:.12em;text-align:center;border-bottom:1px solid var(--border);padding-bottom:var(--sp-4)}[data-hero-pattern="framed-cover"] .region-copy{max-width:var(--layout-hero-copy-ratio,70%);justify-self:var(--layout-hero-align,center)}[data-hero-pattern="framed-cover"] .region-visual{width:100%;}
[data-hero-pattern="portfolio-peek"] .region-stage{grid-template-columns:minmax(0,var(--layout-hero-copy-ratio,60%)) minmax(0,1fr);align-items:start}.region-portfolio-role{grid-column:1 / -1;font-family:var(--font-mono);font-size:var(--fs-12);padding-top:var(--sp-4)}[data-hero-pattern="portfolio-peek"] .region-copy{max-width:none;grid-column:1;grid-row:2}[data-hero-pattern="portfolio-peek"] .region-visual{grid-column:2;grid-row:2;align-self:end;border-radius:var(--r-4);box-shadow:var(--shadow-2)}.region-portfolio-next{grid-column:1 / -1;font-family:var(--font-mono);font-size:var(--fs-14);padding-block:var(--sp-6);border-bottom:1px solid var(--border)}
[data-hero-pattern="type-marquee"] .region-stage{grid-template-columns:1fr;gap:var(--sp-3)}.region-ticker{font-family:var(--font-mono);font-size:var(--fs-12);border-block:1px solid var(--border);padding-block:var(--sp-3);letter-spacing:.18em}[data-hero-pattern="type-marquee"] .region-copy{max-width:var(--layout-hero-copy-ratio,90%)}[data-hero-pattern="type-marquee"] .region-copy h1{font-size:clamp(var(--fs-40),8.5cqi,8rem)}[data-hero-pattern="type-marquee"] .region-visual{;width:100%;border-radius:0}
[data-media-position="background"]{max-width:none;padding:0}[data-media-position="background"] .region-stage{display:flex;flex-direction:column;align-items:var(--layout-hero-align,start);justify-content:flex-end;padding:var(--layout-margin);isolation:isolate}[data-media-position="background"] .region-visual{position:absolute;inset:0;aspect-ratio:auto;border-radius:0;z-index:-1;margin:0}[data-media-position="background"] .region-copy{width:var(--layout-hero-copy-ratio,52%);max-width:none;background:var(--bg);padding:var(--sp-6);margin-top:var(--layout-hero-offset,0px)}.region-cover-scroll{background:var(--bg);font-family:var(--font-mono);font-size:var(--fs-12);padding:var(--sp-3) var(--sp-5);position:relative;z-index:1}
.region-copy{display:flex;flex-direction:column;align-items:var(--layout-hero-align,start)}.region-masthead{margin:0}.region-visual{border:1px solid var(--border)}.region-stage{width:100%;min-width:0;max-width:100%;container-type:inline-size}.region-menu:not([open])>.region-menu-panel{display:none}
[data-hero-pattern="filmstrip"] .region-visual{width:min(100%,calc(var(--layout-hero-min-height,600px) * (var(--layout-hero-media-ratio,16 / 9))));justify-self:center}
[data-media-position="below"]:not([data-hero-pattern="filmstrip"]) .region-stage{grid-template-columns:1fr}[data-media-position="below"]:not([data-hero-pattern="filmstrip"]) .region-copy{grid-column:1;grid-row:auto;max-width:var(--layout-hero-copy-ratio,70%)}[data-media-position="below"]:not([data-hero-pattern="filmstrip"]) .region-visual{grid-column:1;grid-row:auto}
[data-hero-pattern="portfolio-peek"][data-media-position="below"] .region-visual{width:max(32%,calc(100% - var(--layout-hero-copy-ratio,60%)));justify-self:end}
[data-hero-pattern="framed-cover"][data-media-position="right"] .region-stage{grid-template-columns:minmax(0,var(--layout-hero-copy-ratio,60%)) minmax(0,1fr)}[data-hero-pattern="framed-cover"][data-media-position="left"] .region-stage{grid-template-columns:minmax(0,1fr) minmax(0,var(--layout-hero-copy-ratio,40%))}[data-hero-pattern="framed-cover"] .region-cover-label{grid-column:1 / -1;grid-row:1}[data-hero-pattern="framed-cover"][data-media-position="left"] .region-copy,[data-hero-pattern="framed-cover"][data-media-position="left"] .region-visual{grid-row:2}[data-hero-pattern="framed-cover"][data-media-position="right"] .region-copy,[data-hero-pattern="framed-cover"][data-media-position="left"] .region-copy{max-width:none}
[data-media-position="background"] .region-stage{aspect-ratio:var(--layout-hero-media-ratio,var(--layout-hero,16 / 9))}[data-media-position="background"] .region-masthead,[data-media-position="background"] .region-ticker,[data-media-position="background"] .region-specimen-index,[data-media-position="background"] .region-cover-label,[data-media-position="background"] .region-portfolio-role{position:relative;z-index:1;background:var(--bg);padding:var(--sp-3);width:100%;margin:0}[data-media-position="background"] .region-caption{position:relative;z-index:1;background:var(--bg);padding:var(--sp-3);align-self:stretch}[data-media-position="background"] .region-specimen-stamp{background:var(--bg);z-index:1;padding:var(--sp-4)}[data-media-position="background"] .region-portfolio-next{background:var(--bg);padding:var(--sp-4);z-index:1}
[data-media-position="background"] .region-visual{width:100%;max-height:none}
[data-media-position="background"] .region-stage{width:min(100%,calc(var(--layout-hero-min-height,600px) * (var(--layout-hero-media-ratio,16 / 9))));margin-inline:auto}
[data-media-position="background"] .region-copy{min-width:min(100%,24rem)}
.region-footer{min-height:var(--layout-footer-height,360px);padding:var(--sp-10) var(--layout-margin) var(--sp-5);margin-top:var(--layout-section-y);border-top:1px solid var(--border);background:var(--bg-subtle);position:relative;min-width:0}.region-footer a{text-decoration:none}.region-footer a:hover{text-decoration:underline}.region-footer-brand{font-family:var(--font-display);font-size:clamp(var(--fs-32),5cqi,var(--fs-64));line-height:1.05;letter-spacing:var(--ls-tight);display:block;max-width:12ch}.region-footer-grid{display:grid;grid-template-columns:repeat(var(--layout-footer-columns,3),minmax(0,1fr));gap:var(--sp-6)}.region-footer-group h3{font-family:var(--font-mono);font-size:var(--fs-12);margin:0 0 var(--sp-5);color:var(--fg-3)}.region-footer-group a{display:block;font-size:var(--fs-14);padding-block:var(--sp-2)}.region-footer-cta h2{font-family:var(--font-display);font-size:clamp(var(--fs-24),3.8vw,var(--fs-48));line-height:var(--lh-tight);font-weight:var(--fw-medium);margin:0 0 var(--sp-6)}.region-legal{display:flex;justify-content:space-between;gap:var(--sp-4);flex-wrap:wrap;border-top:1px solid var(--border);margin-top:var(--sp-8);padding-top:var(--sp-4);font-family:var(--font-mono);font-size:var(--fs-12);color:var(--fg-3)}
.region-ruled-cells{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,1.5fr);border-block:1px solid var(--border-strong)}.region-ruled-cells> *{padding:var(--sp-6);border-right:1px solid var(--border-strong)}.region-ruled-cells>*:last-child{border-right:0}.region-ruled-cells .region-footer-grid{gap:var(--sp-3)}.region-community-band{font-size:clamp(var(--fs-24),6vw,var(--fs-64));line-height:1.3;text-align:center;border-top:1px solid var(--border-strong);margin-top:var(--sp-5);color:var(--primary-blue);letter-spacing:.12em}
.region-stage-title{font-family:var(--font-display);font-size:clamp(var(--fs-40),9vw,8rem);line-height:1;letter-spacing:var(--ls-tight)}.region-footer-windows{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:var(--sp-8);margin:var(--sp-8) 0}.region-footer-window{border:1px solid var(--border-strong);box-shadow:var(--shadow-2);background:var(--surface);padding:var(--sp-5)}.region-footer-window>span{display:block;font-family:var(--font-mono);font-size:var(--fs-12);border-bottom:1px solid var(--border);padding-bottom:var(--sp-3);margin-bottom:var(--sp-5)}.region-footer-window:last-child{margin-top:var(--sp-10)}.region-footer-ticker{border-block:1px solid var(--border);padding:var(--sp-3);font-family:var(--font-mono);font-size:var(--fs-14)}
.region-studio-top,.region-photo-top{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:var(--sp-8)}.region-address-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--sp-8);margin-top:var(--sp-12);font-size:var(--fs-14)}.region-address-row p{margin:var(--sp-3) 0}.region-address-row>a{align-self:end}.region-footer-photo{margin-top:var(--sp-8);height:clamp(180px,24cqi,360px);overflow:hidden}.region-footer-photo>.fig{object-fit:var(--family-media-fit,cover)}
[data-footer-pattern="centered-cta"]{text-align:center}.region-footer-center-links{display:flex;justify-content:center;gap:var(--sp-6);margin-top:var(--sp-8);flex-wrap:wrap;font-size:var(--fs-14)}.region-footer-watermark{font-family:var(--font-display);font-size:clamp(var(--fs-48),9vw,9rem);line-height:1.1;color:var(--fg-4);margin-top:var(--sp-10);letter-spacing:var(--ls-tight)}
[data-footer-pattern="scenic-overlay"]{padding:0;background:var(--bg)}.region-footer-scene{position:relative;isolation:isolate;min-height:var(--layout-footer-height,480px);padding:var(--layout-margin);display:flex;align-items:flex-end}.region-footer-scene>.fig{position:absolute;inset:0;z-index:-1}.region-scenic-content{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:var(--sp-10);padding:var(--sp-6);background:var(--bg);width:100%;margin-top:var(--sp-20)}[data-footer-pattern="scenic-overlay"]>.region-legal{margin:0;padding:var(--sp-5) var(--layout-margin)}
.region-contact-ledger{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,1.3fr);gap:var(--sp-8)}.region-contact-ledger p{font-size:var(--fs-14)}.region-news-rule{display:block;border-bottom:1px solid var(--border-strong);padding-block:var(--sp-5);font-size:var(--fs-14)}.region-retail-top{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.5fr);gap:var(--sp-10)}.region-retail-groups{display:grid;grid-template-columns:repeat(var(--layout-footer-columns,3),minmax(0,1fr));gap:var(--sp-6)}.region-retail-groups summary{font-family:var(--font-mono);font-size:var(--fs-12);cursor:pointer;padding-block:var(--sp-3)}.region-retail-groups a{display:block;font-size:var(--fs-14);padding-block:var(--sp-2)}.region-retail-locale{display:flex;justify-content:space-between;gap:var(--sp-4);border-block:1px solid var(--border);padding-block:var(--sp-4);margin-block:var(--sp-8);font-size:var(--fs-12)}[data-footer-pattern="retail-accordion"]>.region-footer-brand{font-size:clamp(var(--fs-48),9vw,8rem);max-width:none}
@media (max-width:${theme.token("layout-bp-md", "820px")}){
body:has([data-nav-position="side"]){display:block}.region-nav{max-width:100%;padding-inline:var(--sp-4);gap:var(--sp-3)}.region-brand{font-size:var(--fs-16);max-width:13ch}.region-nav .region-nav-links{display:none}.region-nav-menu{margin-left:auto}.region-nav-numbered{gap:0!important;justify-content:space-between}.region-nav-numbered a{padding:var(--sp-3) var(--sp-2);font-size:var(--fs-12)}.region-nav-chips{gap:var(--sp-1)!important}.region-nav-chips a{display:block;font-size:var(--fs-12);padding:var(--sp-2)}.region-nav-chips span{display:none}.region-nav-segments{gap:0!important}.region-nav-segments a{font-size:var(--fs-12);padding:var(--sp-2)}.region-profile-links{gap:var(--sp-2)}.region-profile-links a{padding:var(--sp-2)}.region-feature-link{font-size:var(--fs-12)}.region-feature-link small{font-size:10px}.region-menu-panel{padding:var(--sp-5);gap:var(--sp-4)}.region-menu-panel nav{flex-wrap:wrap}.region-utility{font-size:10px}.region-nav-main{gap:var(--sp-2)}[data-nav-position="side"]{min-height:var(--layout-nav-height,var(--layout-nav-h,72px));width:100%;border-right:0}[data-nav-pattern="side-rail"]{flex-direction:row;flex-wrap:wrap;gap:var(--sp-3)}.region-rail-note{display:none}.region-nav-vertical{flex-direction:row;flex-wrap:wrap;gap:var(--sp-3)!important}.region-nav-vertical a{font-size:var(--fs-12);padding:var(--sp-2) 0}.region-rail-cta{padding:var(--sp-2);font-size:var(--fs-12);margin:0}[data-nav-pattern="editorial-overlay"] .region-menu-panel{grid-template-columns:1fr}.region-profile-links>a:first-child{display:none}
.region-hero{padding-top:var(--sp-5)}.region-stage{min-height:0;gap:var(--sp-5)}.region-hero .region-stage{grid-template-columns:minmax(0,1fr)}.region-hero .region-copy,.region-hero .region-visual,.region-hero .region-side-note{grid-column:1;grid-row:auto;width:100%;max-width:100%;margin-top:0}.region-copy{order:0}.region-visual{order:1}.region-copy h1{font-size:clamp(var(--fs-32),9vw,var(--fs-48));max-width:var(--layout-hero-title-measure,16ch)}.region-lede{font-size:var(--fs-16)}.region-side-note{display:none}.region-caption{order:3}.region-action-card{flex-wrap:wrap;width:100%}.region-action-card .region-menu{flex:1}.region-masthead{font-size:clamp(var(--fs-32),12vw,var(--fs-48))}.region-product-panel{transform:none}.region-window-bar{font-size:10px}.region-hero[data-hero-pattern="specimen-poster"] .region-stage{padding:var(--sp-4)}.region-specimen-stamp{order:3}.region-film-index{writing-mode:horizontal-tb;text-align:start}.region-hero[data-hero-pattern="filmstrip"] .region-copy{order:2}.region-hero[data-hero-pattern="framed-cover"] .region-stage{padding:var(--sp-5)}.region-portfolio-next{order:3}.region-hero[data-media-position="background"] .region-stage{min-height:var(--layout-hero-min-height,520px);padding-inline:var(--layout-margin)}.region-hero[data-media-position="background"] .region-visual{width:auto;margin:0}.region-hero[data-media-position="background"] .region-copy{width:100%;padding:var(--sp-5)}.region-copy h1{transform:none!important}.region-hero[data-hero-pattern="type-marquee"] .region-copy h1{font-size:clamp(var(--fs-40),11vw,var(--fs-64))}
.region-footer-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--sp-5)}.region-ruled-cells,.region-footer-windows,.region-studio-top,.region-photo-top,.region-address-row,.region-scenic-content,.region-contact-ledger,.region-retail-top{grid-template-columns:minmax(0,1fr)}.region-ruled-cells>*{border-right:0;border-bottom:1px solid var(--border-strong);padding-inline:0}.region-ruled-cells>*:last-child{border-bottom:0}.region-footer-window:last-child{margin-top:0}.region-footer-windows{gap:var(--sp-4)}.region-footer-cta h2{font-size:var(--fs-32)}.region-footer-watermark{font-size:clamp(var(--fs-40),13vw,var(--fs-64))}.region-footer-scene{padding:var(--sp-5)}.region-scenic-content{padding:var(--sp-5);gap:var(--sp-8)}.region-retail-groups{grid-template-columns:minmax(0,1fr)}.region-retail-groups details{border-bottom:1px solid var(--border)}.region-retail-groups summary{font-size:var(--fs-14);padding-block:var(--sp-4)}.region-footer{min-height:0}.region-address-row{gap:var(--sp-5)}.region-footer-group a,.region-retail-groups a{padding-block:var(--sp-2)}
.region-hero[data-hero-pattern] .region-stage{grid-template-columns:minmax(0,1fr)}.region-hero[data-hero-pattern] .region-copy,.region-hero[data-hero-pattern] .region-visual{grid-column:1;grid-row:auto;width:100%;max-width:100%}.region-menu-index{grid-template-columns:minmax(0,1fr)}.region-nav-group{min-width:0}
[data-nav-position="overlay"],[data-nav-position="bottom"]{position:relative;inset:auto;transform:none;width:100%;margin-block:0}body:has([data-nav-position="bottom"]){padding-bottom:0}body:has([data-nav-position="overlay"]) .region-stage{padding-top:var(--sp-6)}[data-nav-position="bottom"] .region-menu-panel{top:100%;bottom:auto}
[data-nav-pattern="segmented-pill"],[data-nav-pattern="mega-feature"],[data-nav-pattern="icon-taxonomy"]{flex-wrap:wrap}.region-nav-segments,.region-nav-numbered,.region-nav-chips{order:3;width:100%;justify-content:center!important}.region-nav-numbered{border-inline:0;border-top:1px solid var(--border)}.region-nav-segments a,.region-nav-numbered a,.region-nav-chips a{white-space:nowrap}.region-nav-segments a{padding:var(--sp-2) var(--sp-4)}
}`;
}
